<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Language" content="en-us">
	<title>404- Y U NO FIND MY PAGE</title>
	<script type="text/javascript" src="<?php echo $home_page; ?>assets/js/jquery/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="<?php echo $home_page; ?>assets/js/common.js"></script>
	<base href="<?php echo $home_page; ?>">
	<script type="text/javascript">
		$(document).ready(function(){
//			$("#center").showCenter();
		});
	</script>
	<style>
		body {
			background-color: #0001AB; font-family: 'Courier New'; color: #fff;
		}

		a {color: #fff}
	</style>
</head>
<body>
<div style="display: table;height: 100%;width: 100%; position: fixed;">
	<div style="display: table-cell;vertical-align: middle; text-align: center;">
		<div style="width: 70%; text-align: left; padding: 0 30px;">
			<p style="color: #0001AB;text-align: right;"><span style="background-color: #fff; ">ERROR 404</span></p>
			<p>
				The page is missing or never was written. You can wait and see if it becomes available again, or you can restart your computer.
				<ul>
					<li>Send us an email to notify this and try it later.</li>
					<li>Press CTRL+ALT+DEL to restart your computer. You will lose unsaved information if any Ming that are running.</li>
				</ul>
			</p>
			<p style="text-align: right">Press any link to continue _</p>
			<p style="text-align: right"><a href="<?php echo $home_page; ?>">Ming.vn</a> |
				<a href="mailto:<?php echo $admin_email; ?>">webmaster</a></p>
		</div>
	</div>
</div>
</body>
</html>