<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Language" content="en-us">
	<title>404- Y U NO FIND MY PAGE</title>
	<script type="text/javascript" src="<?php echo $home_page; ?>assets/js/jquery/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="<?php echo $home_page; ?>assets/js/common.js"></script>
	<base href="<?php echo $home_page; ?>">
	<script type="text/javascript">
		$(document).ready(function(){
//			$("img").showCenter();		?
		});
	</script>
	<style>
		body {font-family: Helvetica, Arial, sans-serif; color: #fff}
		a {color: #fff}
	</style>
</head>
<body style="background-color: #000">
<div style="display: table;height: 100%;width: 100%; position: fixed;">
	<div style="display: table-cell;vertical-align: middle; text-align: center;">
		<img src="http://rwhm.net/error.gif">
		<p style="text-align: center; color:red; font-weight: bold">
			Không tìm thấy trang này!
		</p>
		<p>Trang web bạn yêu cầu có thể đã mất tích! Vui lòng liên hệ với <a href="mailto:<?php echo $admin_email; ?>">ban quản trị</a> để tìm lại.</p>
	</div>
</div>
</body>
</html>