<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Language" content="en-us">
	<title>404- Y U NO FIND MY PAGE</title>
	<script type="text/javascript" src="<?php echo $home_page; ?>assets/js/jquery/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="<?php echo $home_page; ?>assets/js/common.js"></script>
	<base href="<?php echo $home_page; ?>">
	<script type="text/javascript">
		$(document).ready(function(){
//			$("img").showCenter();		?
		});
	</script>
</head>
<body style="background-color: #2D4863">
	<div style="display: table;height: 100%;width: 100%; position: fixed;">
		<div style="display: table-cell;vertical-align: middle; text-align: center;">
			<img src="http://www.troll.me/images/y-u-no/404-y-u-no-found.jpg">
		</div>
	</div>
</body>
</html>