<?php
/** @var \Flywheel\View\Render $this */
use Flywheel\Config\ConfigHandler;

/** @var \Flywheel\Controller\WebController $controller */

/** @var \Menus $parent */

/** @var \Menus[] $lists */

$this->document()->title .= t('Menu Management');
$menu = !empty($menu)? $menu:array();

$this->document()->addCss('css/menu.css');

?>

<div class="page-header">
    <div class="pull-left">
        <h1><?php td('Menu Management') ?></h1>
    </div>
    <div class="pull-right">

    </div>
</div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t('Menu Management') => array(
            'url' => array('menu/default')
        )
    ),
)) ?>

<?php if (!empty($error) || !empty($message)) :?>
    <div class="row-fluid">
        <div class="box">
            <div class="box-content nopadding" style="margin-top:20px;">
                <?php if (isset($error) && !empty($error)) :?>
                    <div class="alert alert-error margin">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <?php echo implode('<br>', array_values($error)); ?>
                    </div>
                <?php elseif (isset($message) && !empty($message)) : ?>
                    <div class="alert alert-success margin">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <?php echo $message; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<div class="row-fluid">
    <div class="span12">
        <div class="box box-color">
            <div class="box-title">
                <h3><?php
                    if ($parent->isRoot()) {td('Menus List');}
                    else {echo $parent->getName();}
                    ?>
                </h3>
            </div>
            <div class="box-content nopadding">
                <table class="table table-nomargin">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th><?php td('Name'); ?></th>
                            <th><?php td('Status'); ?></th>
                            <th><?php td('Language'); ?></th>
                            <th><i class="icon-wrench"></i> </th>
                        </tr>
                    </thead>

                    <?php foreach ($lists as $menu) :
                            $edit_link = $this->createUrl('menu/edit', array('id' => $menu->getId()));
                            $remove_link = $this->createUrl('menu/remove', array('id' => $menu->getId()));
                        ?>
                        <tr id="menu-<?php echo $menu->getId() ?>" class="menu-row">
                            <td><?php echo $menu->getId(); ?></td>
                            <td>
                                <div class="pull-left">
                                    <span style="font-family: sans-serif;"><?php echo (($menu->getLevelValue() > $parent->getLevelValue()-1)? str_repeat('&#8212;', $menu->getLevelValue()-$parent->getLevelValue()-1): '') ?></span>
                                </div>
                                <div class="pull-left">
                                    <strong><?php echo $menu->getName(); ?></strong>&nbsp;&nbsp;
                                    <a href="<?php echo $this->createUrl('menu/default', array('group_id' => $menu->getId()))?>" style="font-size: 12px">
                                        (<?php td('View childs'); ?>)
                                    </a>
                                    <div class="sub-tool" style="font-size: 13px">
                                        <?php
                                        if ($menu->getType() == \Menus::EXTERNAL) {
                                            echo $menu->getLink();
                                        } elseif ($menu->getType() == \Menus::INTERNAL) {
                                            $param = ($menu->getRouteParam())? json_decode($menu->getRouteParam(), true) : array();
                                            $url = str_replace($this->document()->getBaseUrl(), ConfigHandler::get('site_url'), $this->createUrl($menu->getRoute(), $param));
                                            echo '<a href="' .$url .'" target="_blank">' .$url.'</a>';
                                        } else {
                                            echo t($menu->getType());
                                        }
                                        ?>

                                    </div>
                                </div>
                            </td>
                            <td>
                                <?php echo ($menu->getStatus())? t('Active') :t('Inactive'); ?>
                            </td>
                            <td>
                                <?php echo $menu->getLanguage(); ?>
                            </td>
                            <td>
                                <div class="sub-tool">
                                    <a href="<?php echo $edit_link; ?>" class="tool-link tool-edit"><?php td('Edit');?></a>
                                    |
                                    <a href="<?php echo $remove_link ?>" class="tool-link tool-remove"><?php td('Remove'); ?></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th><?php td('Name'); ?></th>
                            <th><?php td('Status'); ?></th>
                            <th><?php td('Language'); ?></th>
                            <th><i class="icon-wrench"></i> </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>