<?php
/** @var \Flywheel\View\Render $this */
use Flywheel\Html\Form;

/** @var \Terms[] $list */

/** @var \Flywheel\Controller\WebController $controller */

/** @var \Terms[] $menu */

$form = new Form('menu-frm');
$this->document()->title .= t('Menu Management');

$select_menu = ($select_menu)? $select_menu : new Menu();
$menu = !empty($menu)? $menu:array();

$this->document()->addCss('menu.css');

?>

<div class="page-header">
    <div class="pull-left">
        <h1><?php td('Menu Management') ?></h1>
    </div>
    <div class="pull-right">

    </div>
</div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t('Menu Management')
    ),
)) ?>

<?php if (!empty($message['global'])) :?>

    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php echo $message['global'] ?>
    </div>
<?php endif; ?>

<?php if (!empty($error)) :?>

    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php echo $error['global'] ?>
    </div>
<?php endif; ?>

<div class="row-fluid">
    <div class="span3">
        <div class="box box-color">
            <div class="box-title"><h3><?php td('Menu'); ?></h3></div>
            <div class="box-content nopadding">
                <?php $form->beginForm(); ?>
                <ul class="menu-list">
                    <?php foreach($menu as $_menu) :?>
                        <li class="menu-row<?php if($select_menu->getId() == $_menu->getId()):?> selected<?php endif; ?>">
                            <a href="<?php echo $this->createUrl('menu/default', array('group_id' => $_menu->getId())); ?>"><?php echo $_menu->getName(); ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div id="new_menu">
                    <h5><?php td('New menu'); ?></h5>
                    <div class="control-group">
                        <div class="controls">
                            <input name="new_menu[name]" value="<?php echo @$input->name ?>" type="text" class="input-block-level" placeholder="<?php td('Type new menu name');?>">
                        </div>
                    </div>

                    <?php $this->widget('app.widget.SelectLanguage', array(
                        'selected' => '*',
                        'elementName' => 'new_menu[language]',
                        'form' => $form
                    ));
                    ?>

                    <div>
                        <button type="submit" class="btn btn-primary"><i class="icon-save"></i> <?php td('Add new menu'); ?></button>
                    </div>
                </div>
                <?php $form->endForm(); ?>
            </div>
        </div>
    </div>
</div>