<?php
use Flywheel\View\Render;

/** @var Render $this */

/** @var \Menus $menu */

$this->document()->addJs('js/menus.js');

$page_title = ($menu->isNew())? t('Add new menu item') : t('Edit menu ' .$menu->getName());
$this->document()->title .= $page_title;

$form = new \Flywheel\Html\Form();
?>


<div class="page-header">
    <div class="pull-left">
        <h1><?php echo $page_title ?></h1>
    </div>
    <div class="pull-right">

    </div>
</div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t('Menu Management') => array(
            'url' => $this->createUrl('menu/default')
        ),
        $page_title
    ),
)) ?>

<?php if (!empty($error) || !empty($message)) :?>
    <div class="row-fluid">
        <div class="box">
            <div class="box-content nopadding" style="margin-top:20px;">
                <?php if (isset($error) && !empty($error)) :?>
                    <div class="alert alert-error margin">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <?php echo implode('<br>', array_values($error)); ?>
                    </div>
                <?php elseif (isset($message) && !empty($message)) : ?>
                    <div class="alert alert-success margin">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <?php echo $message; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php
$form->beginForm();
?>
<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-content">
                <div class="control-group<?php if(isset($error['menus.name'])) echo ' error' ?>">
                    <label class="big"><?php td('Name'); ?></label>
                    <input name="menus[name]" value="<?php echo $menu->getName() ?>" class="input-huge" id="menu-name" placeholder="<?php echo t('Enter Menu Name Here') ?>">
                    <?php if (isset($error['menus.name'])) : ?>
                        <span class="help-block"><?php echo $error['menus.name'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="control-group<?php if(isset($error['parent'])) echo ' error' ?>">
                    <label class="big"><?php td('Parent'); ?></label>
                    <?php $this->widget('app.widget.SelectMenus', array(
                        'label' => t('Select Parent'),
                        'selected' =>  ($menu->isNew())? 0 :$menu->getParent()->getId(),
                        'elementName' => 'parent_id',
                        'form' => $form,
                    )) ;?>
                    <?php if (isset($error['parent'])) : ?>
                        <span class="help-block"><?php echo $error['parent'] ?></span>
                    <?php endif; ?>
                </div>

                <?php $this->widget('app.widget.SelectLanguage', array(
                    'selected' => $menu->getLanguage(),
                    'elementName' => 'menus[language]',
                    'form' => $form
                )) ?>

                <div class="control-group">
                    <label class="control-label"><?php echo t('Status'); ?> </label>
                    <div class="controls">
                        <?php $form->radioButton('menus[status]', $menu->getStatus())
                            ->add(1, 'Active', array('class' => 'radio inline'), array('class' => 'styled'))
                            ->add(0, 'Inactive', array('class' => 'radio inline'), array('class' => 'styled'))
                            ->display(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-content" style="background-color: #f3f3f3; margin-top: 48px;">
                <div class="control-group<?php if(isset($error['menus.type'])) echo ' error' ?>">
                    <label class="big"><?php td('Type'); ?></label>
                    <?php
                    $form->radioButton('menus[type]', $menu->getType())
                        ->add('internal', t('internal link'), array('class' => 'radio inline _menus-type'))
                        ->add('external', t('external link'), array('class' => 'radio inline _menus-type'))
                        ->add('separate', t('separate'), array('class' => 'radio inline _menus-type'))
                        ->display();
                    ?>
                    <?php if (isset($error['menus.type'])) : ?>
                        <span class="help-block"><?php echo $error['menus.type'] ?></span>
                    <?php endif; ?>
                </div>

                <!-- External Link -->
                <div id="external-form" class="_extra-form<?php if($menu->getType() != 'external') :?> hide<?php endif; ?>">
                    <div class="control-group<?php if(isset($error['menus.link'])) echo ' error' ?>">
                        <label class="big"><?php td('Link'); ?></label>
                        <input name="menus[link]" class="input-xlarge" type="text" id="menus-link" placeholder="http://" value="<?php echo $menu->getLink(); ?>">
                        <?php if (isset($error['menus.link'])) : ?>
                            <span class="help-block"><?php echo $error['menus.link'] ?></span>
                        <?php endif; ?>
                    </div>

                    <div class="control-group<?php if(isset($error['menus.target'])) echo ' error' ?>">
                        <label class="big"><?php td('Target'); ?></label>
                        <?php
                            $form->selectOption('menus[target]', $menu->getTarget())
                                ->addOption(t('self'), '_self')
                                ->addOption(t('blank'), '_blank')
                                ->addOption(t('parent'), '_parent')
                                ->display();
                        ?>
                        <?php if (isset($error['menus.target'])) : ?>
                            <span class="help-block"><?php echo $error['menus.target'] ?></span>
                        <?php endif; ?>
                    </div>
                </div>
                <!--/ external link -->

                <!-- Internal link -->
                <div id="internal-form" class="_extra-form<?php if($menu->getType() != 'internal') :?> hide<?php endif; ?>">
                    <div class="control-group<?php if(isset($error['menus.route'])) echo ' error' ?>">
                        <label class="big"><?php td('Route'); ?></label>
                        <input name="menus[route]" class="input-xlarge" type="text" id="menus-route" value="<?php echo $menu->getRoute(); ?>">
                        <?php if (isset($error['menus.route'])) : ?>
                            <span class="help-block"><?php echo $error['menus.route'] ?></span>
                        <?php endif; ?>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Parameter (json)</label>
                        <textarea class="input-block-level" rows="5" name="menus[route_param]"><?php echo $menu->getRouteParam() ?></textarea>
                    </div>
                </div>
                <!-- /internal link -->
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="form-actions text-center">
            <button type="submit" class="btn btn-large btn-primary">&nbsp;&nbsp; <i class="icon-save"></i> <?php td('Save'); ?> &nbsp;&nbsp;</button>
            <a href="<?php echo $this->createUrl('menu/default'); ?>"> <?php td('Cancel'); ?></a>
        </div>
    </div>
</div>
<?php
$form->endForm();
?>