<div class="breadcrumbs">
    <ul>
        <?php foreach ($activesLink as $activeLink) : ?>
            <li><a href="<?php echo $activeLink['url'] ?>"><?php echo $activeLink['label'] ?></a>
                <i class="icon-angle-right"></i>
            </li>
        <?php endforeach; ?>

        <?php
        if(isset($inActiveLink)) {
            foreach ($inActivesLink as $inActiveLink) : ?>
                <li class="active"><a><?php echo $inActiveLink ?></a></li>
            <?php endforeach; ?>
        <?php } ?>
    </ul>
</div>