<div class="control-group<?php if(!empty($error)? ' error' : '') ?> .">
    <label class="control-label"><?php echo $label ?></label>
    <div class="controls">
        <?php echo $select->display(); ?>
    </div>
    <?php if (!empty($error)) :
        if (!is_array($error)) {
            $error = implode('. ', $error);
        }
        ?>
        <span class="help-block"><?php echo implode('. ', $error) ?></span>
    <?php endif; ?>
</div>