<?php
/** @var \CalendR\Calendar $calendar */

use Toxotes\Cms;

$month = $calendar->getMonth($current_year, $current_month);
$month->setFirstWeekday(\CalendR\Period\Day::SUNDAY);
?>
<div class="ui-datepicker-inline ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
    <!-- Header -->
    <div class="ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all">
        <a class="ui-datepicker-prev ui-corner-all" data-month="<?php echo $month->getPrevious()->format('m') ?>" data-year="<?php echo $month->getPrevious()->format('Y') ?>" title="Prev">
            <span class="ui-icon ui-icon-circle-triangle-w" data-month="<?php echo $month->getPrevious()->format('m') ?>" data-year="<?php echo $month->getPrevious()->format('Y') ?>"><?php Cms::td('Prev'); ?></span></a>

        <a class="ui-datepicker-next ui-corner-all" data-month="<?php echo $month->getNext()->format('m') ?>" data-year="<?php echo $month->getNext()->format('Y') ?>" title="Next">
            <span class="ui-icon ui-icon-circle-triangle-e" data-month="<?php echo $month->getNext()->format('m') ?>" data-year="<?php echo $month->getNext()->format('Y') ?>" ><?php Cms::td('Next'); ?></span></a>

        <div class="ui-datepicker-title">
            <span class="ui-datepicker-month"><?php echo $current_month ?></span> /
            <span class="ui-datepicker-year"><?php echo $current_year ?></span>
        </div>

    </div>
    <!--/header -->

    <table>
        <!-- Weeks -->
        <thead>
        <tr>
            <th class="ui-datepicker-week-end"><span title="Sunday"><?php Cms::td('Sun'); ?></span></th>
            <th><span title="Monday"><?php Cms::td('Mon'); ?></span></th>
            <th><span title="Tuesday"><?php Cms::td('Tue'); ?></span></th>
            <th><span title="Wednesday"><?php Cms::td('Wed'); ?></span></th>
            <th><span title="Thursday"><?php Cms::td('Thur'); ?></span></th>
            <th><span title="Friday"><?php Cms::td('Fri'); ?></span></th>
            <th class="ui-datepicker-week-end"><span title="Saturday"><?php Cms::td('Sat'); ?></span></th>
        </tr>
        </thead>
        <!--/weeks -->
        <?php foreach ($month as $week): ?>
            <tr>
                <?php // Iterate over your month and get days ?>
                <?php foreach ($week as $day):
                    /** @var \CalendR\Period\Day $day */
                    ?>
                    <?php //Check days that are out of  your month
                    $td_class = "ui-datepicker-days-cell-over";
                    $a_class = "ui-state-default";
                    if ($day->format('d') == $current_day && $day->format('m') == $current_month) {
                        $td_class .= " ui-datepicker-current-day ui-datepicker-today";
                        $a_class .= " ui-state-highlight ui-state-active";
                    }

                    if ($day->format('l') == 'Sunday' || $day->format('l') == 'Saturday') {
                        $td_class .= "ui-datepicker-week-end";
                    }

                    if ($day->format('m') != $current_month) {
                        $td_class .= ' ui-datepicker-other-month ';
                    }

                    $route_params['day'] = $day->format('d');
                    $route_params['month'] = $day->format('m');
                    $route_params['year'] = $day->format('Y');

                    ?>
                    <td class="<?php echo $td_class; ?>">
                        <a class="<?php echo $a_class;?>" href="<?php echo $controller->createUrl($route, $route_params); ?>"><?php echo $day->format('d'); ?></a>
                    </td>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
    </table>
</div>