<div class="ui-datepicker-inline ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all"
     style="display: block;">
    <div class="ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all"><a
            class="ui-datepicker-prev ui-corner-all" data-handler="prev" data-event="click" title="Prev"><span
                class="ui-icon ui-icon-circle-triangle-w">Prev</span></a><a class="ui-datepicker-next ui-corner-all"
                                                                            data-handler="next" data-event="click"
                                                                            title="Next"><span
                class="ui-icon ui-icon-circle-triangle-e">Next</span></a>

        <div class="ui-datepicker-title"><span class="ui-datepicker-month">July</span>&nbsp;<span
                class="ui-datepicker-year">2013</span></div>
    </div>
    <table class="ui-datepicker-calendar">
        <thead>
        <tr>
            <th class="ui-datepicker-week-end"><span title="Sunday">Su</span></th>
            <th><span title="Monday">Mo</span></th>
            <th><span title="Tuesday">Tu</span></th>
            <th><span title="Wednesday">We</span></th>
            <th><span title="Thursday">Th</span></th>
            <th><span title="Friday">Fr</span></th>
            <th class="ui-datepicker-week-end"><span title="Saturday">Sa</span></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class=" ui-datepicker-week-end ui-datepicker-other-month " data-handler="selectDay"
                data-event="click" data-month="5" data-year="2013"><a class="ui-state-default ui-priority-secondary"
                                                                      href="#">30</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">1</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">2</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">3</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">4</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">5</a></td>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">6</a></td>
        </tr>
        <tr>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">7</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">8</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">9</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">10</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">11</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">12</a></td>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">13</a></td>
        </tr>
        <tr>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">14</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">15</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">16</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">17</a></td>
            <td class=" ui-datepicker-days-cell-over  ui-datepicker-current-day ui-datepicker-today"
                data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default ui-state-highlight ui-state-active" href="#">18</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">19</a></td>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">20</a></td>
        </tr>
        <tr>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">21</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">22</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">23</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">24</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">25</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">26</a></td>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">27</a></td>
        </tr>
        <tr>
            <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="6"
                data-year="2013"><a class="ui-state-default" href="#">28</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">29</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">30</a></td>
            <td class=" " data-handler="selectDay" data-event="click" data-month="6" data-year="2013"><a
                    class="ui-state-default" href="#">31</a></td>
            <td class=" ui-datepicker-other-month " data-handler="selectDay" data-event="click" data-month="7"
                data-year="2013"><a class="ui-state-default ui-priority-secondary" href="#">1</a></td>
            <td class=" ui-datepicker-other-month " data-handler="selectDay" data-event="click" data-month="7"
                data-year="2013"><a class="ui-state-default ui-priority-secondary" href="#">2</a></td>
            <td class=" ui-datepicker-week-end ui-datepicker-other-month " data-handler="selectDay"
                data-event="click" data-month="7" data-year="2013"><a class="ui-state-default ui-priority-secondary"
                                                                      href="#">3</a></td>
        </tr>
        </tbody>
    </table>
</div>