<?php
/** @var \Flywheel\View\Render $this */

$submit_btn_name = ($user->isNew())? 'Create' : 'Save';

$form = $this->createFrom('user_frm');
$form->setHtmlOption(array(
    'class' => 'form-horizontal',
));
?>


<div class="page-header">
    <div class="pull-left">
        <h1><?php echo ($user->isNew()? t('Create New User') : t('Edit User')); ?></h1>
    </div>
    <div class="pull-right">
        <ul class="minitiles">
            <li class="teal">
                <a href="<?php echo $this->createUrl('roles/default') ?>"><i class="icon-group"></i></a>
            </li>
            <li class="red">
                <a href="<?php echo $this->createUrl('roles/permission') ?>"><i class="icon-cogs"></i></a>
            </li>
            <li class="lime">
                <a href="<?php echo $this->createUrl('user/default') ?>"><i class="icon-th-list"></i></a>
            </li>
        </ul>
    </div>
</div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t('Users Management') => array(
            'url' => array('user'),
        ),
        ($user->isNew()? t('Create New User') : t('Edit User'))
    ),
)) ?>

<div class="row-fluid">
    <div class="span12">
        <div class="box-title">
            <h3><i class="icon-edit"></i> <?php echo $page_title ?></h3>
        </div>

        <div class="box-content">
            <!-- User From -->
            <?php $form->beginForm(); ?>
            <fieldset>
                <!-- General form elements -->
                <div class="widget row-fluid">
                    <?php if (isset($error) && !empty($error)) :?>
                        <div class="alert alert-error margin">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <?php echo implode('<br>', array_values($error)); ?>
                        </div>
                    <?php elseif (isset($message) && !empty($message)) : ?>
                        <div class="alert alert-success margin">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <?php echo $message; ?>
                        </div>
                    <?php endif; ?>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Username'); ?> *</label>
                        <div class="controls">
                            <?php if ($user->isNew()) :?>
                                <input value="<?php echo $user->getUsername() ?>" type="text" name="user[username]" class="input-xlarge" placeholder="<?php echo t('From 3-16 character'); ?>">
                            <?php else : ?>
                                <strong><?php echo $user->getUsername() ?></strong>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Password'); ?> *</label>
                        <div class="controls">
                            <input value="<?php echo $new_password ?>" type="password" name="new_password" class="input-xlarge">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Confirm password'); ?> *</label>
                        <div class="controls">
                            <input value="" type="password" name="confirm_password" class="input-xlarge" placeholder="<?php echo t('Type password again'); ?>">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Full name'); ?> *</label>
                        <div class="controls">
                            <input value="<?php echo $user->getName() ?>" type="text" name="user[name]" class="input-xlarge">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Email'); ?> *</label>
                        <div class="controls">
                            <input value="<?php echo $user->getEmail() ?>" type="text" name="user[email]" class="input-xlarge">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Phone number'); ?></label>
                        <div class="controls">
                            <input value="<?php echo $user->getPhoneNumber() ?>" type="text" name="user[phone_number]" class="input-xlarge">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Status'); ?> </label>
                        <div class="controls">
                            <?php $form->radioButton('user[status]', $user->getStatus())
                                ->add(1, 'Active', array('class' => 'radio inline'), array('class' => 'styled'))
                                ->add(0, 'Inactive', array('class' => 'radio inline'), array('class' => 'styled'))
                                ->display(); ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Banned'); ?> </label>
                        <div class="controls">
                            <?php $form->radioButton('user[banned]', $user->getBanned())
                                ->add(1, 'Yes', array('class' => 'radio inline'), array('class' => 'styled'))
                                ->add(0, 'No', array('class' => 'radio inline'), array('class' => 'styled'))
                                ->display(); ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Email activate'); ?> </label>
                        <div class="controls">
                            <?php $form->radioButton('user[active_email]', $user->getActiveEmail())
                                ->add(1, 'Yes', array('class' => 'radio inline'), array('class' => 'styled'))
                                ->add(0, 'No', array('class' => 'radio inline'), array('class' => 'styled'))
                                ->display(); ?>
                        </div>
                    </div>

                    <?php if (!$user->isNew()) : ?>
                        <div class="control-group">
                            <label class="control-label"><?php echo t('Register time'); ?> </label>
                            <div class="controls">
                                <?php echo $user->getRegisterTime(); ?>
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label"><?php echo t('Last login time'); ?> </label>
                            <div class="controls">
                                <?php echo $user->getLastVisitTime(); ?>
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="form-actions align-right">
                        <button type="submit" class="btn btn-info"><?php echo t($submit_btn_name) ?></button>
                        <button type="reset" class="btn"><?php echo t('Reset') ?></button>
                    </div>
                </div>
                <!-- /general form elements -->

            </fieldset>
            <?php $form->endForm(true); ?>
        </div>
        <!-- /user form -->
    </div>
</div>