<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <base href="<?php $this->document()->getBaseUrl(); ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->document()->title ;?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Favicons -->

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/images/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/images/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/images/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/images/icons/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="assets/images/icons/favicon.png">

    <!--[if lt IE 9]>
    <script src="assets/js/minified/core/html5shiv.min.js"></script>
    <script src="assets/js/minified/core/respond.min.js"></script>
    <![endif]-->

    <!-- Fides Admin CSS Core -->

    <link rel="stylesheet" type="text/css" href="assets/css/minified/aui-production.min.css">

    <!-- Theme UI -->

    <link id="layout-theme" rel="stylesheet" type="text/css" href="assets/themes/minified/fides/color-schemes/dark-blue.min.css">

    <!-- Fides Admin Responsive -->

    <link rel="stylesheet" type="text/css" href="assets/themes/minified/fides/common.min.css">
    <link rel="stylesheet" type="text/css" href="assets/themes/minified/fides/responsive.min.css">

    <!-- Fides Admin JS -->

    <script type="text/javascript" src="assets/js/minified/aui-production.min.js"></script>
    <?php echo $this->document()->js('TOP'); ?>
</head>

<body style="background-color: #f3f3f3">
    <div id="loading" class="ui-front loader ui-widget-overlay bg-white opacity-100">
        <img src="assets/images/loader-dark.gif" alt="">
    </div>
    <div class="ui-widget-overlay bg-black opacity-60"></div>
<?php echo $buffer; ?>
</body>
<?php echo $this->document()->js('BOTTOM'); ?>
</html>