<?php /** @var \LatestNews $widget */
use Toxotes\Cms;

if (!empty($widget->list)) :
?>
<div class="block lst-training">
    <h3 class="title rs">
        <?php echo $widget->getOwner()->getName(); ?>
        <a href="<?php echo $controller->createUrl('category/default', array('id' => $widget->getParams('term_id'))) ?>" class="more">
            <?php Cms::td('View more'); ?><i class="icon iPickReadR"></i>
        </a>
    </h3>
    <div class="block-content">
    <?php
        $i = 0;
    ?>
    <?php foreach($widget->list as $item) :
            $excerpt = $item->getExcerpt();
            if (!$excerpt) {
                $excerpt = mb_substr(strip_tags($item->getContent(), '<br><span>'), 0, 255, 'UTF-8') .'...';
            }
        ?>
        <div class="train-item clearfix">
            <?php if ($item->getMainImg()) :?>
                <a href="<?php echo $controller->createUrl('post/detail', array('id' => $item->getId())); ?>" class="thumb">
                    <img src="<?php echo $item->displayMainImg();?>" alt="<?php echo $item->getTitle() ?>">
                </a>
            <?php endif; ?>

            <div class="wrap-content">
                <h4 class="rs title">
                    <a href="<?php echo $controller->createUrl('post/detail', array('id' => $item->getId())); ?>"><?php echo $item->getTitle() ?></a>
                    <?php if ($i < 3) :?>
                        <i class="icon-hotnews"></i>
                    <?php endif; ?>
                </h4>
                <p class="rs date"><?php echo $item->getCreatedTime()->format(Cms::t('d/m/Y')) ?></p>
                <p class="rs lead-news"><?php echo $excerpt ;?></p>
            </div>
        </div>
        <?php ++$i; ?>
    <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>