<?php
use Flywheel\View\Render;

/** @var Render $this */
/** @var Posts[] $posts */
/** @var Terms $cat */

$page_title = $cat->getName();
$this->document()->title = $page_title;

$breadcrumbs = array(
    'links' => array(
        t('Home') => array(
            'url' => $this->document()->getBaseUrl()
        ),
    )
);

$breadcrumbs['links'][] = $page_title;

if ($cat->getLevel() == 3) {
    $all_id = $cat->getId();
    $children = $cat->getChildren();
} else {
    $parent = $cat->getParent();
    $all_id =  $parent->getId();
    $children = $parent->getChildren();
}

$all_link = $controller->createUrl('events/default', array('id' => $all_id));

?>

<?php $this->widget('app.widget.Breadcrumbs', $breadcrumbs) ?>

<div class="fixCenter1K">
    <div id="training-event" class="row l656 fixCenter1K">
        <!-- Left -->
        <div class="col">
            <div id="all-event">
                <!-- Quick filter -->
                <div class="quick-filter">
                    <span class="fw-b">
                        <a href="<?php echo $all_link ?>"><?php td('All'); ?></a> :
                    </span>
                    <?php
                        for($i = 0, $size = sizeof($children); $i < $size; ++$i) :?>
                        <a href="<?php echo $controller->createUrl('events/default', array('id' => $children[$i]->getId())); ?>"<?php if($children[$i]->getId() == $cat->getId()) : ?> class="active"<?php endif; ?>>
                            <?php echo $children[$i]->getName(); ?>
                        </a>
                        <?php if ($i != $size-1) :?>&nbsp;/&nbsp;<?php endif; ?>
                    <?php endfor; ?>
                </div>
                <!-- /quick filter -->

                <div class="lst-event">
                    <?php  foreach($posts as $post) :
                        $excerpt = $post->getExcerpt();
                        if (!$excerpt) {
                            $excerpt = mb_substr(strip_tags($post->getContent(), '<br><span>'), 0, 255, 'UTF-8') .'...';
                        }
                        $properties = PostPeer::getPostProperties($post->getId());
                        ?>
                        <div class="event-item media">
                            <div class="duration-time">
                                <div class="box-time">
                                <?php
                                    $start_date = $properties['event_start_date']->getValue()->format('d-m-Y');
                                    $end_date = $properties['event_end_date']->getValue()->format('d-m-Y');
                                ?>
                                <?php if ($start_date != $end_date) : ?>
                                <?php echo $start_date ;?> - <?php echo $end_date; ?>
                                <?php else : ?>
                                    <?php echo $start_date ;?>
                                <?php endif; ?>
                                </div>
                                <?php
                                    $now = new DateTime();
                                    $interval = $now->diff($properties['event_start_date']->getValue());
                                ?>
                                <?php if (($now > $start_date) && ($interval->s > (3600*24))) : ?>
                                <div class="time-left">
                                    <span class="line-through"></span>
                                    <span class="val"><span class="fw-b"><?php td($interval->days . '</span>days left'); ?>
                                </div>
                                <?php endif; ?>
                            </div>

                            <div class="media-body">
                                <h4 class="name-event rs">
                                    <a href="<?php echo $controller->createUrl('events/detail', array('id' => $post->getId()))?>"><?php echo $post->getTitle() ?></a>
                                </h4>
                                <p class="event-term" style="margin-top: 0"><em><?php echo Terms::retrieveById($post->getTermId())->getName() ;?></em></p>
                                <p class="desc-event rs"><?php echo $excerpt ;?></p>
                                <!--<p class="rs link-action">
                                <a href="#">Read more</a>
                                <span class="sep">|</span>
                                <a href="#">Comment</a>
                                <span class="sep">|</span>
                                <a href="#"><i class="icon iNote"></i>Register Now</a>
                            </p> -->
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <!-- Pagination -->
            <div class="news-paging">
                <?php
                $route[0] = 'events/default';
                foreach ($_GET as $k=>$v) {
                    $route[$k] = $v;
                }

                $this->widget('app.widget.FrontendPagination', array(
                    'pageSize' => $page_size,
                    'total' => $total,
                    'currentPage' => $this->request()->get('page', 'INT', 1),
                    'route' => $route,
                ));
                ?>
            </div>
        </div>
        <!--/left -->

        <!-- Right -->
        <div class="col">
            <div id="news-cat-right-col">
                <?php $this->widget('app.widget.AjaxCalendar', array(
                    'term_id' => $cat->getId(),
                    'fetch_child' => true,
                    'route_params' => array('id' => $cat->getId()),
                    'day' => $this->request()->get('day'),
                    'month' => $this->request()->get('month'),
                    'year' => $this->request()->get('year'),
                )); ?>

                <?php
                $keyword = $this->request()->get('keyword');
                $route = $_GET;
                unset($route['page']);
                ?>

                <form class="search-box-common clearfix" method="get" action="<?php echo $controller->createUrl('events/default', $route); ?>">
                    <label for="keyword">
                        <input id="keyword" name="keyword" value="<?php echo $keyword; ?>" type="text" placeholder="<?php td('Search here...'); ?>">
                    </label>
                    <input type="submit" class="buttons" value="<?php td('Find') ;?>">
                </form>

                <?php $this->widget('app.widget.ArchivesWidget', array(
                    'cat_id' => $cat->getId(),
                    'year' => $this->request()->get('year')
                ))
                ?>
            </div>
        </div>
        <!--/right -->
    </div>
</div>