<?php
use Flywheel\View\Render;

/** @var Render $this */
/** @var Posts $event */
/** @var Terms $cat */

$page_title = $event->getTitle();
$this->document()->title = $page_title;

$properties = PostPeer::getPostProperties($event->getId());

$this->document()->addJs('http://maps.google.com/maps/api/js?sensor=false&language=en', 'TOP');
$this->document()->addJs('assets/js/plugins/gmap/gmap3.min.js', 'TOP');
$this->document()->addJs('assets/js/events.js');
$this->document()->addJsCode("jQuery('.place-maps').gmap3({
            marker:{
                address: '" .$properties['event_location_address']->getValue() ."'
            },
            map:{
                options:{
                    zoom: 15
                }
            }
        }).css({'width' : '312px', 'height': '200px'}).show();");
?>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Home') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        $cat->getName() => array(
            'url' => $controller->createUrl('events/default', array('id' => $cat->getId()))
        ),
        ($page_title)
    ),
)) ?>

<div id="event-detail" class="row l656 fixCenter1K">
    <div class="col">
        <div class="art-full-info">
            <h2 class="rs art-title"><?php echo $event->getTitle() ;?></h2>
            <div class="art-ultility clearfix">
                <div class="date-created">
                    <span><?php echo $cat->getName(); ?></span>
                </div>
                <div class="art-tool">
                        <span class="like-fb">
                            <iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $controller->createUrl('events/detail', array('id' => $event->getId()));?>&amp;layout=button_count&amp;show_faces=false&amp;width=450&amp;action=like&amp;font&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:74px; height:20px;" allowtransparency="true"></iframe>
                        </span>
                    <span class="sep"></span>
                        <span>
                            <i class="icon iEmail"></i>
                            Email
                        </span>
                    <span class="sep"></span>
                        <span>
                            <i class="icon iPrinter"></i>
                            Print
                        </span>
                </div>
            </div>
            <div class="event-fixed-time">
                <?php
                    $start_date = $properties['event_start_date']->getValue()->format('d/m/Y');
                    $end_date = $properties['event_end_date']->getValue()->format('d/m/Y');
                    $start_time = $properties['event_start_date']->getValue()->format('H:i');
                    $end_time = $properties['event_end_date']->getValue()->format('H:i');
                ?>
                <i class="icon iClock"></i>
                <?php if ($start_date != $end_date) : ?>
                    <?php if ($start_time != '00:00') {echo $start_time;} ?> <?php echo $start_date; ?> -
                    <?php if ($end_time != '00:00') {echo $end_time;} ?> <?php echo $end_date; ?>
                <?php else : ?>
                    <?php if ($start_time != '00:00' && $end_time != '00:00') {
                        echo $start_time .' - ' .$end_time;
                    } elseif ($start_time != '00:00') {
                        echo $start_time;
                    } else if ($end_time != '00:00') {
                        echo $end_time;
                    }?>
                    <?php echo $start_date; ?>
                <?php endif; ?>
            </div>
            <div class="event-fixed-time">
                <i class="icon iPlace"></i> <?php echo $properties['event_location_address']->getValue(); ?>
            </div>

            <div class="text-content">
                <p><?php echo $event->getExcerpt()?><br> <?php echo $event->getContent(); ?></p>
            </div>

        </div>

        <?php if ($others) :?>

        <div class="block">
            <h3 class="title"><?php td('Other Events'); ?></h3>
            <div class="block-content">
                <ul class="rs lst-other-event">
                    <?php foreach ($others as $o) :?>
                    <li>
                        <a href="<?php echo $controller->createUrl('events/detail', array('id' => $o->getId())) ?>">
                            <span class="fw-b"><?php echo $o->getTitle(); ?></span>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php endif; ?>
    </div>

    <div class="col">
        <div class="place-maps"></div>

        <p class="fw-b"><?php td('Contact Infomation'); ?></p>
        <p class="rs"><?php echo $properties['event_contact_name']->getValue() ?></p>
        <p class="rs"><?php echo $properties['event_contact_address']->getValue() ?></p>
        <p class="rs">Phone: <span class="fw-b"><?php echo $properties['event_contact_phone']->getValue() ?></span></p>
        <p class="rs">Fax: <span class="fw-b"><?php echo $properties['event_contact_fax']->getValue() ?></span></p>
        <p class="rs">Email: <span class="fw-b"><?php echo $properties['event_contact_email']->getValue() ?></span></p>
    </div>
</div>