<?php
use Flywheel\Document\Html;
/** @var Html $document */
$document = $this->document();
?>
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Apple devices fullscreen -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <!-- Apple devices fullscreen -->
    <meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <base href="<?php echo $document->getBaseUrl() ?>">
    <title><?php echo $document->title; ?></title>
    <?php echo $document->css(); ?>
    <?php echo $document->js('TOP'); ?>

    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico" />
    <!-- Apple devices Homescreen icon -->
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png" />

</head>

<body>
<div id="navigation">
    <?php $this->widget('app.Widget.Navigator'); ?>
    <?php $this->widget('app.Widget.MobileNavigator'); ?>
</div>

<div class="container-fluid" id="content">
    <!-- BEGIN Left Slide bar -->

    <?php $this->widget('app.Widget.SideBar'); ?>
    <!-- END Left Slide bar -->
    <div id="main">
        <div class="container-fluid">
            <?php echo $buffer ?>
        </div>
    </div>
</div>

</body>
<?php echo $document->js('BOTTOM'); ?>
</html>
