<h3>Change Password: # <?php echo $user->id ?></h3>
<br>
<br>

<form action="" method="post">
    <div class="column-left">
        <div class="box-header">
            <h1>CHANGE PASSWORD</h1>
        </div>
        <p>
        <div style="color: #1623cf">
            <h3><?php echo $user->email; ?></h3>
        </div>
        </p>
        <p>
            <label><b>NEW PASSWORD:</b></label>
            <input type="password" id="new_pass" name="new_pass" />
        </p>
        <p>
            <label><b>CONFIRM PASSWORD:</b></label>
            <input type="password" id="con_pass" name="con_pass" />
        </p>
    </div>
    <div class="clear"></div>
    <div class="action_bar">
        <input type="submit" name="submit" class="button blue" value="CHANGE" />
    </div>


</form>