<?php /* @Consumer $consumer */ ?>
<form method="post" >
    <div class="column-left">
        <p>
            <label><b>EMAIL:</b></label>
            <input type="text" id="email" name="email" />
        </p>
        <p>
            <label><b>PASSWORD:</b></label>
            <input type="password" id="password" name="password" />
        </p>
        <p>
            <label><b>CONFIRM PASSWORD:</b></label>
            <input type="password" id="con_password" name="con_password" />
        </p>
        <p>
            <label><b>FULL NAME:</b></label>
            <input type="text" id="full_name" name="full_name" />
        </p>
        <p>
            <label><b>PHONE:</b></label>
            <input type="text" id="phone" name="phone" />
        </p>
        <p>
            <label><b>STATUS:</b></label>
            <select name="status" id="status" "	>
            <option value="1" >ACTIVE</option>
            <option value="0" >INACTIVE</option>
            </select>
        </p>
        <p>
            <label><b>BANNED:</b></label>
            <select name="banned" id="banned" "	>
            <option value="0" >NO</option>
            <option value="1" >YES</option>
            </select>
        </p>
    </div>
    <div class="clear"></div>
    <div class="action_bar">
        <input type="submit" name="submit" class="button blue" value="Submit Post" />
        <a href="#modal" class="modal button">Cancel</a>
    </div>
</form>