<?php
use Flywheel\Html\DataGrid\Row;
use Flywheel\Html\DataGrid\Table;

/** @var \Flywheel\View\Render $this */

/** @var \Users[] $users */

/** @var \Flywheel\Controller\WebController $controller */

?>

<h5 class="widget-name"><i class="icon-columns"></i><?php echo t('Users management'); ?></h5>

<!-- Begin user list -->
<div class="widget">
    <!--<div class="navbar"><div class="navbar-inner"><h6>Default datatable</h6></div></div>-->
    <?php if (sizeof($users) == 0) : ?>
        <div class="alert alert-info">
            <strong><?php echo t('No results found!') ?></strong>
        </div>
    <?php else :?>

    <div class="table-overflow">
        <table class="table table-striped table-bordered" id="data-table">
            <thead>
                <tr>
                    <th><label>
                            <input type="checkbox" id="check-all"> &darr;
                        </label></th>
                    <th><?php echo t('Username'); ?></th>
                    <th><?php echo t('Email'); ?></th>
                    <th><?php echo t('Full name'); ?></th>
                    <th><?php echo t('Active'); ?></th>
                    <th><?php echo t('Banned'); ?></th>
                    <th><?php echo t('Active email'); ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            <?php for($i = 0, $size = sizeof($users); $i < $size; ++$i) : ?>
                <tr>
                    <td><label>
                            <input type="checkbox" class="check-list" value="<?php echo $users[$i]->getId() ?>">
                        </label>
                    </td>

                    <td><strong><?php echo $users[$i]->getUsername() ?></strong></td>

                    <td><a href="mailto:<?php echo $users[$i]->getEmail() ?>"><?php echo $users[$i]->getEmail() ?></td>

                    <td><?php echo $users[$i]->getName() ?></td>

                    <td><?php echo ($users[$i]->getStatus()? t('Yes') : t('No')) ?></td>

                    <td><?php echo ($users[$i]->getBanned()? t('Yes') : t('No')) ?></td>

                    <td><?php echo ($users[$i]->getActiveEmail()? t('Yes') : t('No')) ?></td>

                    <td>&nbsp;</td>
                </tr>
            <?php endfor; ?>
            </tbody>
        </table>
    </div>

    <?php endif; ?>
</div>
<!-- /end user list -->