<?php
use Flywheel\Html\DataGrid\Row;
use Flywheel\Html\DataGrid\Table;

/** @var \Flywheel\View\Render $this */

/** @var \Users[] $users */

/** @var \Flywheel\Controller\WebController $controller */

$currentUser = BackendAuth::getInstance()->getUser();

$this->document()->addJs('js/files/user.js');

?>

<div class="page-header">
    <div class="page-title">
        <h3><?php echo t('Users Management') ?></h3>
    </div>

    <div class="page-stats">
        <a href="<?php echo $this->createUrl('user/create') ?>" class="btn btn-large btn-info">
            <i class="icon-plus"></i>&nbsp;<?php echo t('Add New User') ?>
        </a>
    </div>
</div>

<!-- Actions Wrapper -->
<div class="actions-wrapper">
    <div class="actions" data-easytabs="true">
    </div>
</div>
<!--/ actions wrapper -->

<h5 class="widget-name"><i class="icon-columns"></i><?php echo t('Users List'); ?></h5>

<!-- Search Form -->
<div class="row-fluid">
    <?php
    $form = $this->createFrom('search-user', $this->createUrl('user'), 'GET');
    $form->setHtmlOption(array(
        'class' => 'form-horizontal',
    ));
    $form->beginForm();

    ?>
    <div class="widget">
        <div class="row-fluid">
            <div class="span5">
                <input name="keyword" class="span12" type="text" value="<?php echo $keyword ?>" placeholder="<?php echo t('Find by username or email'); ?>">
            </div>
            <div class="span3">
                    <?php $form->selectOption('status', ('' != $status? $status : null), array(
                                    'class' => 'styled'))
                                ->addOption('Status', '')
                                ->addOption('Active', 1)
                                ->addOption('Inactive', 0)
                                ->display(); ?>
            </div>
            <div class="span4">
                    <?php $form->selectOption('banned', ('' != $banned? $banned : null), array(
                        'class' => 'styled'))
                        ->addOption('Banned', '')
                        ->addOption('Yes', 1)
                        ->addOption('No', 0)
                        ->display(); ?>
                    <button class="btn pull-right">
                        <i class="icon-search"></i>&nbsp;
                        <?php echo t('Find') ?>
                    </button>
            </div>
        </div>
    </div>
    <?php $form->endForm(false); ?>
</div>
<!--/search form -->


<!-- Begin user list -->
<div class="widget">
    <!--<div class="navbar"><div class="navbar-inner"><h6>Default datatable</h6></div></div>-->
    <?php if (sizeof($users) == 0) : ?>
        <div class="alert alert-info">
            <strong><?php echo t('No results found!') ?></strong>
        </div>
    <?php else :?>

    <div class="table-overflow">
        <table class="table table-striped table-bordered" id="data-table">
            <thead>
                <tr>
                    <th><label>
                            <input type="checkbox" id="check-all"> &darr;
                        </label></th>
                    <th width="20%"><?php echo t('Username'); ?></th>
                    <th><?php echo t('Email'); ?></th>
                    <th><?php echo t('Full name'); ?></th>
                    <th><?php echo t('Active'); ?></th>
                    <th><?php echo t('Banned'); ?></th>
                    <th><?php echo t('Active email'); ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            <?php for($i = 0, $size = sizeof($users); $i < $size; ++$i) : ?>
                <tr id="user-row-<?php echo $users[$i]->getId() ?>">
                    <td><label>
                            <input type="checkbox" class="check-list" value="<?php echo $users[$i]->getId() ?>">
                        </label>
                    </td>

                    <td><strong><?php echo $users[$i]->getUsername() ?></strong></td>

                    <td><a href="mailto:<?php echo $users[$i]->getEmail() ?>"><?php echo $users[$i]->getEmail() ?></td>

                    <td><?php echo $users[$i]->getName() ?></td>

                    <td><?php echo ($users[$i]->getStatus()? t('Yes') : t('No')) ?></td>

                    <td><?php echo ($users[$i]->getBanned()? t('Yes') : t('No')) ?></td>

                    <td><?php echo ($users[$i]->getActiveEmail()? t('Yes') : t('No')) ?></td>

                    <td>
                        <!-- edit link -->
                        <a class="btn btn-mini tool-edit" href="<?php echo $this->createUrl('user/edit/', array('id' => $users[$i]->getId()))?>">
                            <i class="ico-pencil"></i> <?php echo t('Edit') ?>
                        </a>

                        <?php if ($currentUser->getId() != $users[$i]->getId()) : ?>
                        <!-- remove link -->
                        <a class="btn btn-mini btn-danger tool-remove" data-id="<?php echo $users[$i]->getId() ?>" href="<?php echo $this->createUrl('user/delete') ?>">
                            <i class="ico-remove"></i> <?php echo t('Remove') ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endfor; ?>
            </tbody>
        </table>
    </div>

    <?php endif; ?>
</div>
<!-- /end user list -->