<h3>Edit: # <?php echo $user->id ?></h3>
<br>
<br>

<form action="" method="post">
    <div class="column-left">
        <div class="box-header">
            <h1>EDIT USER</h1>
        </div>
        <p>
            <div style="color: #1623cf">
                <h3><?php echo $user->email; ?></h3>
            </div>
        </p>
        <p>
            <label><b>FULL NAME:</b></label>
            <input type="text" id="full_name" name="full_name" value="<?php echo $user->full_name; ?>"/>
        </p>
        <p>
            <label><b>PHONE:</b></label>
            <input type="text" id="phone" name="phone" value="<?php echo $user->phone; ?>" />
        </p>
        <p>
            <label><b>STATUS:</b></label>
            <select name="status" id="status" "	>
            <option value="1" >ACTIVE</option>
            <option value="0" >INACTIVE</option>
            </select>
        </p>
        <p>
            <label><b>BANNED:</b></label>
            <select name="banned" id="banned" "	>
            <option value="0" >NO</option>
            <option value="1" >YES</option>
            </select>
        </p>
    </div>
    <div class="clear"></div>
    <div class="action_bar">
        <input type="submit" name="submit" class="button blue" value="EDIT" />
    </div>


</form>