<?php
/** @var \Flywheel\View\Render $this */
/** @var Posts $post */
/** @var PostImages[] $postImages */
/** @var PostAttachments[] $postAttachments */

use Flywheel\Html\Form;
use Toxotes\Plugin;

$doc = $this->document();
$this->document()->addCss('css/plugins/fileupload/jquery.fileupload-ui.css');
$this->document()->addCss('css/post.css');


$doc->addJs('js/handlebars-v2.0.0.js', 'TOP');
$doc->addJs('js/plugins/fileupload/jquery.fileupload.js', 'TOP');
$doc->addJs('js/process/post_form.js');

$form = new Form('post');
$form->setHtmlOption(array(
    'class' => 'form-vertical'
));
$taxonomy_label = Plugin::getTaxonomyOption($taxonomy, 'post', 'label', t('Post'));


if ($post->getIsDraft() && !$post->getTitle()) {
    $page_title = t('Create New ' .$taxonomy_label);
} else {
    $page_title = t('Edit ' .$post->getTitle());
}

$this->document()->title .= $page_title;

$taxonomy = ($taxonomy)? $taxonomy : 'post';
?>
    <div class="page-header">
        <div class="pull-left">
            <h1><?php echo $page_title; ?></h1>
        </div>
        <div class="pull-right">
            <ul class="minitiles">
                <li class="lime">
                    <a href="<?php echo $this->createUrl('post/default', array('taxonomy' => $taxonomy)) ?>"><i class="icon-th-list"></i></a>
                </li>
            </ul>
        </div>
    </div>

<?php $this->widget('app.Widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        $taxonomy_label => array(
            'url' => array('post/default', array('taxonomy' => $taxonomy)),
        ),
        $page_title
    ),
)) ?>

<?php if (!empty($error) || !empty($message)) :?>
<div class="row-fluid">
    <div class="box">
        <div class="box-content nopadding" style="margin-top:20px;">
            <?php if (isset($error) && !empty($error)) :?>
                <div class="alert alert-error margin">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo implode('<br>', array_values($error)); ?>
                </div>
            <?php elseif (isset($message) && !empty($message)) : ?>
                <div class="alert alert-success margin">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $message; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endif; ?>

<div id="post-frm">
<?php $form->beginForm(); ?>
<div class="row">
    <!-- POST TITLE -->
    <div class="col-md-12 post-title-txt-ctn">
        <div class="box-content nopadding">
            <div class="form-group<?php if(isset($error['posts.title'])) echo 'has-error' ?>">
                <input name="post[title]" value="<?php echo $post->getTitle() ?>" class="form-control big" id="post-title" placeholder="<?php echo t('Enter Title here') ?>">
                <?php if (isset($error['posts.title'])) : ?>
                    <span class="help-block"><?php echo $error['posts.title'] ?></span>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <!--/post title -->

    <?php Plugin::doAction('custom_after_' .$taxonomy .'_post_common_info_box', $post, $form, $error); ?>

    <!-- COMMON INFO -->
    <div class="col-md-12">
        <div class="box-content nopadding">
            <div class="col-md-3 nopadding form-group<?php if(isset($error['posts.term_id'])) echo ' has-error' ?>">
                <label class="control-label col-md-12 nopadding"><?php td('Category'); ?> (*)</label>
                <div class="col-md-12 nopadding">
                    <?php $this->widget('app.Widget.SelectPostCategory', array(
                        'label' => t('Select Category'),
                        'taxonomy' => $taxonomy,
                        'selected' => $post->getTermId(),
                        'elementName' => 'post[term_id]',
                        'error' => isset($error['posts.term_id'])? $error['posts.term_id']: null,
                        'form' => $form,
                        'htmlOptions' => ['class' => 'form-control']
                    ));
                    ?>
                    <?php if (isset($error['posts.term_id'])) : ?>
                        <span class="help-block"><?php echo $error['posts.term_id'] ?></span>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <!--/common info -->

    <!-- Editor -->
    <div class="col-md-12">
        <div class="box">
            <div class="box-content nopadding">
                <div class="form-group">
                    <label class="control-label"><?php td('Intro'); ?></label>
                    <?php
                    $excerpt = \Flywheel\Util\Sanitize::stripNewline($post->getExcerpt());
                    ?>
                    <textarea name="post[excerpt]" class="form-control" rows="3"><?php echo $excerpt;  ?></textarea>
                </div>

                <div class="form-group">
                    <label class="control-label big"><?php td('Content'); ?> (*)</label>
                    <?php $this->widget(\Flywheel\Config\ConfigHandler::get('editor'), array(
                        'selector' => '#post-content',
                        'height' => 360
                    )); ?>
                    <textarea name="post[content]" id="post-content" class="form-control"><?php echo $post->getContent() ?></textarea>
                </div>
            </div>
        </div>
    </div>
    <!--/editor -->

    <?php Plugin::doAction('custom_after_' .$taxonomy .'_post_common_info_box', $post, $form, $error); ?>

    <!-- OTHER INFO -->
    <div class="col-md-3">
        <div class="box box-condensed">
            <div class="box-title">
                <h3><?php td("Common Information") ?></h3>
            </div>
            <div class="box-content">
                <div class="form-group<?php if(isset($error['posts.language'])) echo ' has-error' ?>">
                    <label class="control-label"><?php echo t('Language'); ?></label>
                    <div class="controls">
                        <?php $this->widget('app.Widget.SelectLanguage', array(
                            'selected' => $post->getLanguage(),
                            'elementName' => 'post[language]',
                            'form' => $form,
                            'htmlOptions' => [
                                'class' => 'form-control'
                            ]
                        )) ?>

                        <?php if (isset($error['posts.language'])) : ?>
                            <span class="help-block"><?php echo $error['posts.language'] ?></span>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label"><?php echo t('Status'); ?></label>
                    <div class="controls">
                        <?php
                        $statusOpt = $form->selectOption('post[status]', $post->getStatus(), [
                            'class' => 'form-control'
                        ])
                            ->addOption(t('Publish'), 'PUBLISH')
                            ->addOption(t('Unpublish'), 'UNPUBLISH');

                        $statusOpt = Plugin::applyFilters('custom_' .$taxonomy .'_status_options', $statusOpt);
                        $statusOpt->display();
                        ?>
                    </div>
                </div>

                <div class="form-group<?php if(isset($error['posts.ordering'])) echo ' has-error' ?>">
                    <label class="control-label col-md-4 nopadding"><?php td('Ordering') ;?></label>
                    <div class="col-md-6 pull-left">
                        <input name="post[ordering]" type="text" class="form-control" value="<?php echo $post->getOrdering(); ?>">
                        <?php if (isset($error['posts.ordering'])) : ?>
                            <span class="help-block"><?php echo $error['posts.ordering'] ?></span>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-group<?php if(isset($error['posts.is_pin'])) echo ' has-error' ?> col-md-12 nopadding" style="margin: 10px 0">
                    <label class="control-label  col-md-4 nopadding"><?php td('Highlight') ;?></label>
                    <div class="col-md-8">
                        <?php $form->radioButton('posts[is_pin]', $post->getIsPin())
                            ->add(1, t('Yes'), array('class' => 'inline'))
                            ->add(0, t('No'), array('class' => 'inline'))
                            ->display();
                        ?>
                        <?php if (isset($error['posts.is_pin'])) : ?>
                            <span class="help-block"><?php echo $error['posts.is_pin'] ?></span>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/other info -->

    <!-- POST IMAGES -->
    <div class="col-md-6" id="post-images-frm">
        <div class="box box-condensed box-condensed">
            <div class="box-title">
                <h3><?php td("Images") ?></h3>
                <div class="actions">
                    <div class="btn btn-danger fileinput-button">
                        <i class="fa fa-cloud-upload"></i> <?php td("Add image") ?>
                        <input id="_post-img-upload" type="file" name="upload_images" multiple="" data-post-id="<?php echo $post->getId(); ?>">
                    </div>
                </div>
            </div>
            <div class="box-content" id="_post-images-ctn">
            </div>
        </div>
    </div>
    <!--/post images -->
</div>

<?php Plugin::doAction('custom_before_' .$taxonomy .'_post_form', $post, $form, $error); ?>

<div class="row">
    <div class="col-md-12 form-actions text-center" style="background-color: #efefef; margin: 20px 0">
        <button name="submit" type="submit" class="btn btn-primary">&nbsp;&nbsp;&nbsp;
            <i class="fa fa-save"></i>&nbsp;&nbsp;&nbsp;
            <?php echo t('SAVE POST'); ?>&nbsp;&nbsp;&nbsp;
        </button>
    </div>
</div>
<input name="post_id" value="<?php echo $post->getId()?>" type="hidden">
<input name="post[taxonomy]" value="<?php echo $taxonomy; ?>" type="hidden">
<?php $form->endForm(); ?>
</div>

<script type="text/x-handlebars-template" id="_post-img-tmp">
    {{#if images}}
    <table class="table table-condensed" id="post-img-tbl">
        <tbody>
        {{#each images}}
        <tr id="post-img-{{id}}">
            <td class="col-md-2">
                <a href="{{url}}" target="_blank"><img src="{{thumb_url}}" width="100%"></a>
            </td>
            <td class="col-md-7">
                <div class="col-md-2 nopadding">
                    <label for="img_ordering" class="control-label"><?php td("Ordering") ?></label>
                    <input type="text" name="img_ordering" class="form-control" value="{{ordering}}" id="_img-ordering-txt-{{id}}">
                </div>
                <div class="col-md-10">
                    <label class="control-label"><?php td("Caption") ?></label>
                    <div class="input-group">
                        <input type="text" name="img_caption" placeholder="<?php td("Edit caption") ?>" value="{{caption}}" class="form-control" id="_img-caption-txt-{{id}}">
                        <div class="input-group-btn">
                            <button class="btn _save-img" type="button" data-img="{{id}}"><i class="fa fa-save"></i> </button>
                        </div>
                    </div>
                    <div><p><small>{{date created_time}}</small></p></div>
                </div>
            </td>
            <td class="col-md-3 text-right item-tool">
                <div class="item-img-tool-ctn{{#unless is_main}} normal{{else}} post-main-img-ctn{{/unless}}">
                    {{#if is_main}}
                    <span class="item-img-tool"><i class="fa fa-star"></i></span>
                    {{else}}
                    <a class="item-img-tool make-star _set-main-img" rel="{{id}}" href="javascript:void(0);" title="<?php td("Main image") ?>">
                        <i class="fa fa-star"></i>
                    </a>
                    {{/if}}

                    <a class="item-img-tool" href="{{url}}" title="<?php td("View full size") ?>" target="_blank">
                        <i class="fa fa-search"></i>
                    </a>

                    <a class="item-img-tool _remove-img" rel="{{id}}" href="javascript:void(0);" title="<?php td("Remove") ?>">
                        <i class="fa fa-close"></i>
                    </a>
                </div>
            </td>
        </tr>
        {{/each}}
        </tbody>
    </table>
    {{/if}}
</script>