<?php
/** @var \Flywheel\View\Render $this */
/** @var \WidgetBlock $widgetBlock */

$submit_btn_name = ($widgetBlock->isNew())? 'Create' : 'Save';

$this->document()->addJs('js/widget_block.js');

$page_title = ($widgetBlock->isNew())? t('Create New Widget') : t('Edit ' .$widgetBlock->getName());

$this->document()->title .= $page_title;

$form = $this->createFrom('widget_block_frm');
$form->setHtmlOption(array(
    'class' => 'form-horizontal',
));
?>


<div class="page-header">
    <div class="pull-left">
        <h1><?php echo $page_title ?></h1>
    </div>
    <div class="pull-right">
        <ul class="minitiles">
            <li class="teal">
                <a href="<?php echo $this->createUrl('widget/default') ?>"><i class="icon-th-list"></i></a>
            </li>
        </ul>
    </div>
</div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t('Widget Management') => array(
            'url' => array('user'),
        ),
        $page_title
    ),
)) ?>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-edit"></i> <?php echo $page_title ?></h3>
            </div>
            <div class="box-content">
                <!-- User From -->
                <?php $form->beginForm(); ?>
                <fieldset>
                    <!-- General form elements -->
                    <div class="widget row-fluid">
                        <?php if (isset($error) && !empty($error)) :?>
                            <div class="alert alert-error margin">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                <?php echo implode('<br>', array_values($error)); ?>
                            </div>
                        <?php elseif (isset($message) && !empty($message)) : ?>
                            <div class="alert alert-success margin">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                <?php echo $message; ?>
                            </div>
                        <?php endif; ?>

                        <div class="control-group">
                            <label class="control-label<?php if(isset($error['widget_block.name'])) echo ' error' ?>"><?php echo t('Name'); ?> *</label>
                            <div class="controls">
                                <input value="<?php echo $widgetBlock->getName() ?>" type="text" name="input[name]" class="input-xlarge" placeholder="<?php td('Block Name'); ?>">
                                <?php if (isset($error['widget_block.name'])) : ?>
                                    <span class="help-block"><?php echo implode('. ', $error['widget_block.name']) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <?php $this->widget('app.widget.SelectWidgetBlock', array(
                            'label' => t('Type'),
                            'elementName' => 'input[path]',
                            'htmlOptions' => array(
                                'data-widget-id' => $widgetBlock->getId()
                            ),
                            'selected' => ($widgetBlock->isNew()? '*':$widgetBlock->getPath())
                        ));
                        ?>

                        <div class="control-group">
                            <label class="control-label<?php if(isset($error['widget_block.position'])) echo ' error' ?>"><?php echo t('Position'); ?> *</label>
                            <div class="controls">
                                <?php $this->widget('app.widget.SelectWidgetPosition', array(
                                        'elementName' => 'input[position]',
                                        'select' => $widgetBlock->getPosition(),
                                        'form' => $form
                                ));?>
                                <?php if (isset($error['widget_block.position'])) : ?>
                                    <span class="help-block"><?php echo implode('. ', $error['widget_block.position']) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <?php $this->widget('app.widget.SelectLanguage', array(
                            'selected' => $widgetBlock->language,
                            'elementName' => 'input[language]',
                            'form' => $form
                        ));
                        ?>

                        <div class="control-group">
                            <label class="control-label"><?php echo t('Status'); ?> *</label>
                            <div class="controls">
                                <?php $form->radioButton('input[status]', $widgetBlock->getStatus())
                                    ->add(1, 'Active', array('class' => 'radio inline'), array('class' => 'styled'))
                                    ->add(0, 'Inactive', array('class' => 'radio inline'), array('class' => 'styled'))
                                    ->display(); ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label"><?php echo t('Note'); ?> </label>
                            <div class="controls">
                                <textarea name="input[note]" class="input-block-level input-xlarge"><?php echo $widgetBlock->getNote();?></textarea>
                            </div>
                        </div>

                        <?php if (!$widgetBlock->isNew()) : ?>
                            <div class="control-group">
                                <label class="control-label"><?php echo t('Created time'); ?> </label>
                                <div class="controls">
                                    <?php echo $widgetBlock->getCreatedTime() ?>
                                </div>
                            </div>


                            <div class="control-group">
                                <label class="control-label"><?php echo t('Last modified time'); ?> </label>
                                <div class="controls">
                                    <?php echo $user->getModifiedTime(); ?>
                                </div>
                            </div>
                        <?php endif; ?>

                        <div class="form-actions align-right">
                            <button type="submit" class="btn btn-primary"><?php echo t($submit_btn_name) ?></button>
                            <button type="reset" class="btn"><?php echo t('Reset') ?></button>
                        </div>
                    </div>
                    <!-- /general form elements -->

                </fieldset>
                <?php $form->endForm(true); ?>
            </div>
        </div>
    </div>
    <div class="span6">
        <div class="box box-color green">
            <div class="box-title">
                <h3><?php td('Widget Options'); ?></h3>
            </div>

            <div class="box-content" id="_wb-options-form">
                <?php echo $extends_form ?>
            </div>
        </div>
    </div>
</div>