<?php
/** @var \Flywheel\View\Render $this */

/** @var \Users[] $users */

/** @var \Flywheel\Controller\WebController $controller */

$addNewFrm = new Flywheel\Html\Form('add-new-term');
$addNewFrm->setHtmlOption(array(
    'class' => 'form-no-widget'
));

$this->document()->title .= $page_title;

?>

<div class="page-header">
    <div class="pull-left">
        <h1><?php echo $page_title ?></h1>
    </div>
    <div class="pull-right">

    </div>
</div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t($page_title)
    ),
)) ?>

<?php if ('' != $message) :?>

    <div class="alert<?php if(!empty($error)):?> alert-error<?php endif; ?>">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php echo $message ?>
    </div>
<?php endif; ?>


<div class="row-fluid">

    <!-- Add Term Form -->
    <div class="span4">
        <div class="box box-color box-bordered">
            <div class="box-title">
                <h3><?php echo t('Add New') ?></h3>
            </div>

            <div class="box-content">
                <?php $addNewFrm->beginForm() ?>

                <div class="control-group<?php if(isset($error['terms.name'])) echo ' error' ?>">
                    <label class="control-label"><?php echo t('Name') ?> (*)</label>
                    <div class="controls">
                        <input type="text" class="span12" name="term[name]" value="<?php echo @$inputTerm->name ?>">
                        <?php if (isset($error['terms.name'])) : ?>
                            <span class="help-block"><?php echo implode('. ', $error['terms.name']) ?></span>
                        <?php endif; ?>
                    </div>
                </div>

                <?php
                $this->widget('app.widget.SelectParentTerm', array(
                    'taxonomy' => $taxonomy,
                    'selected' => isset($inputTerm->term_parent)? $inputTerm->term_parent : 0,
                    'elementName' => 'term_parent',
                    'error' => isset($error['terms.parent'])? $error['terms.parent']: null,
                    'form' => $addNewFrm,
                ));
                ?>

                <?php $this->widget('app.widget.SelectLanguage', array(
                    'selected' => '*',
                    'elementName' => 'term[language]',
                    'form' => $addNewFrm
                ));
                ?>

                <div class="control-group<?php if(isset($error['terms.description'])) echo ' error' ?>">
                    <label class="control-label"><?php echo t('Description') ?></label>
                    <div class="controls">
                        <textarea rows="5" cols="5" name="term[description]" class="span12"><?php echo @$inputTerm->description ?></textarea>
                        <?php if (isset($error['terms.description'])) : ?>
                            <span class="help-block"><?php echo implode('. ', $error['terms.description']) ?></span>
                        <?php endif; ?>
                    </div>
                </div>

                <?php \Toxotes\Plugin::doAction($taxonomy .'_add_form_fields') ?>

                <div class="form-actions align-center">
                    <button type="submit" class="btn btn-primary"><?php echo t('Add New') ?></button>
                </div>

                <input name="term[taxonomy]" value="<?php echo $taxonomy ?>" type="hidden">
                <?php $addNewFrm->endForm() ?>
            </div>
        </div>
    </div>
    <!-- /add term form -->

    <!-- Term list -->
    <div class="span8">
        <div class="box box-color">
            <div class="box-title">
                <h3>
                    <i class="icon-reorder"></i>
                    <?php td('Categories'); ;?>
                </h3>
            </div>

            <div class="box-content nopadding">
                <?php $table->display(); ?>
            </div>
        </div>
    </div>
    <!-- /term list -->
</div>