<?php
/** @var \Flywheel\View\Render $this */

/** @var \Users[] $users */

/** @var \Flywheel\Controller\WebController $controller */

$addNewFrm = new Flywheel\Html\Form('add-new-term');
$addNewFrm->setHtmlOption(array(
    'class' => 'form-column form-horizontal'
));

$title = \Toxotes\Plugin::getTaxonomyOption($taxonomy, 'post', 'label');
$page_title = t($title .' Management');

$this->document()->title .= $page_title;

$this->document()->addJs('category.js');

?>

<div class="page-header">
    <div class="pull-left">
        <h1><?php echo $page_title ?></h1>
    </div>
    <div class="pull-right">

    </div>
</div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t($page_title)
    ),
)) ?>

<?php if ('' != $message) :?>

    <div class="alert<?php if(!empty($error)):?> alert-error<?php endif; ?>">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php echo $message ?>
    </div>
<?php endif; ?>

<div class="row-fluid">
    <?php $addNewFrm->beginForm() ?>
    <div class="span12">
        <div class="box box-color">
            <div class="box-title">
                <h3><?php td('Add new') ?></h3>
            </div>

            <div class="box-content nopadding">

                <div class="span6">
                    <div class="control-group<?php if(isset($error['terms.name'])) echo ' error' ?>">
                        <label class="control-label"><?php echo t('Name') ?> (*)</label>
                        <div class="controls">
                            <input type="text" class="span12" name="term[name]" value="<?php echo @$inputTerm->name ?>">
                            <?php if (isset($error['terms.name'])) : ?>
                                <span class="help-block"><?php echo implode('. ', $error['terms.name']) ?></span>
                            <?php endif; ?>
                        </div>
                    </div>

                    <?php
                    $this->widget('app.widget.SelectParentTerm', array(
                        'taxonomy' => $taxonomy,
                        'selected' => isset($inputTerm->term_parent)? $inputTerm->term_parent : 0,
                        'elementName' => 'term_parent',
                        'error' => isset($error['terms.parent'])? $error['terms.parent']: null,
                        'form' => $addNewFrm,
                    ));
                    ?>

                    <?php $this->widget('app.widget.SelectLanguage', array(
                        'selected' => '*',
                        'elementName' => 'term[language]',
                        'form' => $addNewFrm
                    ));
                    ?>
                </div>

                <div class="span6">

                    <div class="control-group<?php if(isset($error['terms.description'])) echo ' error' ?>">
                        <label class="control-label"><?php echo t('Description') ?></label>
                        <div class="controls">
                            <textarea rows="5" cols="5" name="term[description]" class="span12"><?php echo @$inputTerm->description ?></textarea>
                            <?php if (isset($error['terms.description'])) : ?>
                                <span class="help-block"><?php echo implode('. ', $error['terms.description']) ?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <?php if ($taxonomy == 'category') :?>
                <div class="span12">
                    <div class="control-group">
                        <label class="control-label"><?php echo t('Category View') ?></label>
                        <div class="controls">
                            <?php $this->widget('app.widget.SelectCategoryView', array(
                                'form' => $addNewFrm,
                            )) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Post View') ?></label>
                        <div class="controls">
                            <?php $this->widget('app.widget.SelectPostView', array(
                                'form' => $addNewFrm
                            )) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Ordering'); ?></label>
                        <div class="controls">
                            <?php
                            $postOrderingOpt = $addNewFrm->selectOption('property[post_ordering]')
                                ->addOption(t('Default'), 'default')
                                ->addOption(t('Date Create'), 'created_time')
                                ->addOption(t('Date Modified'), 'modified_time')
                                ->addOption(t('Post Ordering'), 'ordering');
                            $postOrderingOpt->display();
                            ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php echo t('Page Size'); ?></label>
                        <div class="controls">
                            <?php
                            $postOrderingOpt = $addNewFrm->selectOption('property[page_size]')
                                ->addOption(5, 5)
                                ->addOption(10, 10)
                                ->addOption(15, 15)
                                ->addOption(25, 25)
                                ->addOption(50, 50)
                                ->addOption(t('Unlimited'), -1);
                            $postOrderingOpt->display();
                            ?>
                        </div>
                    </div>
                </div>
                <?php endif; ?>

                <?php \Toxotes\Plugin::doAction($taxonomy .'_add_form_fields') ?>

                <div class="span12 text-center" style="background-color: #efefef; margin: 0; padding: 10px;">
                    <button type="submit" class="btn btn-primary"><?php echo t('Add New') ?></button>
                </div>
                <input name="term[taxonomy]" value="<?php echo $taxonomy ?>" type="hidden">
            </div>
        </div>
    </div>
    <?php $addNewFrm->endForm() ?>
</div>

<div class="row-fluid">
    <!-- Term list -->
    <div class="span12">
        <div class="box box-color">
            <div class="box-title">
                <h3>
                    <i class="icon-reorder"></i>
                    <?php echo $title ?>
                </h3>
            </div>

            <div class="box-content nopadding">
                <?php $table->display(); ?>
            </div>
        </div>
    </div>
    <!-- /term list -->
</div>