<?php
$this->document()->title .= $page_title;
$this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t($page_title)
    ),
)) ?>

<div class="page-header">
    <div class="page-title">
        <h3><?php echo t($page_title) ?></h3>
    </div>

    <div class="page-stats">&nbsp;
    </div>
</div>

<!-- Actions Wrapper -->
<div class="actions-wrapper">
    <div class="actions" data-easytabs="true">
    </div>
</div>
<!--/ actions wrapper -->

<div class="span12">
    <div class="well">
        <div class="control-group">
            <label class="control-label"><?php echo t('Are you sure?') ?></label>
            <div class="controls">
                <form action="" method="POST">
                    <input type="submit" name="submit" value="<?php echo t('REMOVE') ?>">
                    <a href="<?php $this->createUrl('category', array('taxonomy' => $taxonomy)) ?>"><?php echo t('Cancel') ?></a>
                </form>
            </div>
        </div>
    </div>
</div>