<?php
$this->document()->title .= $page_title;
$form = new \Flywheel\Html\Form('edit-term-frm');
$form->setHtmlOption(array('class'=>'form-horizontal'));
?>

<div class="page-header">
    <div class="pull-left">
        <h1><?php echo $page_title ?></h1>
    </div>
    <div class="pull-right">
        <ul class="minitiles">
            <li class="lime">
                <a href="<?php echo $this->createUrl('user/default', array('taxonomy' => $taxonomy)) ?>"><i class="icon-th-list"></i></a>
            </li>
        </ul>
    </div>
</div>

<?php
$this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        \Toxotes\Plugin::getTaxonomyOption($taxonomy, 'post', 'label') => array(
            'url' => array('category/default', array('taxonomy' => $taxonomy))
        ),
        t($page_title)
    ),
)); ?>

<div class="row-fluid">
    <div class="box">
        <div class="box-title">
            <i class="icon-edit"></i>
            <?php td('Edit ' .$term->getName()); ?>
        </div>

        <div class="box-content">
            <?php $form->beginForm(); ?>
            <div class="control-group<?php if(isset($error['terms.name'])) echo ' error' ?>">
                <label class="control-label"><?php echo t('Name') ?> (*)</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" name="term[name]" value="<?php echo @$inputTerm->name ?>">
                    <?php if (isset($error['terms.name'])) : ?>
                        <span class="help-block"><?php echo implode('. ', $error['terms.name']) ?></span>
                    <?php endif; ?>
                </div>
            </div>

            <?php
            $this->widget('app.widget.SelectParentTerm', array(
                'taxonomy' => $taxonomy,
                'selected' => $parent,
                'elementName' => 'term_parent',
                'error' => isset($error['terms.parent'])? $error['terms.parent']: null,
                'form' => $form,
            ));
            ?>

            <?php $this->widget('app.widget.SelectLanguage', array(
                'selected' => $inputTerm->language,
                'elementName' => 'term[language]',
                'form' => $form
            ));
            ?>

            <div class="control-group<?php if(isset($error['terms.description'])) echo ' error' ?>">
                <label class="control-label"><?php echo t('Description') ?></label>
                <div class="controls">
                    <textarea rows="5" cols="5" name="term[description]" class="input-xlarge"><?php echo @$inputTerm->description ?></textarea>
                    <?php if (isset($error['terms.description'])) : ?>
                        <span class="help-block"><?php echo implode('. ', $error['terms.description']) ?></span>
                    <?php endif; ?>
                </div>
            </div>

            <?php \Toxotes\Plugin::doAction($taxonomy .'_add_form_fields') ?>

            <div class="form-actions align-center">
                <button type="submit" class="btn btn-primary"><?php echo t('Save') ?></button>
            </div>

            <input name="term[taxonomy]" value="<?php echo $taxonomy ?>" type="hidden">
            <?php $form->endForm(); ?>
        </div>
    </div>
</div>