<?php
$this->document()->addCss('css/plugins/icheck/all.css');

$this->document()->addJs('js/plugins/icheck/jquery.icheck.min.js', 'TOP');
$this->document()->addJs('js/plugins/validation/jquery.validate.min.js', 'TOP');
$this->document()->addJs('js/plugins/validation/jquery.validate.min.js', 'TOP');

$form = new \Flywheel\Html\Form('login-form');
$form->setHtmlOption([
    'class' => 'form-validate',
]);
?>
<div class="wrapper">
    <h1>TOXOTES ADMIN CP</h1>
    <div class="login-body">
        <h2 class="text-uppercase"><?php td('Sign in'); ?></h2>

        <?php if (!empty($error)) : ?>
            <div class="alert alert-danger alert-dismissable">
                <strong><?php td('Warning'); ?>!</strong><br>
                <?php echo implode('<br>', $error); ?>
            </div>
        <?php endif; ?>

        <?php $form->beginForm(); ?>
            <div class="form-group">
                <div class="email controls">
                    <input type="text" name='credential' placeholder="<?php td("Email address") ?>" class='form-control' data-rule-required="true" data-rule-email="true" value="<?php echo $display; ?>">
                </div>
            </div>
            <div class="form-group">
                <div class="pw controls">
                    <input type="password" name="password" placeholder="<?php td("Password") ?>" class='form-control' data-rule-required="true">
                </div>
            </div>
            <div class="form-group">
                <div class="language controls">
                    <?php
                        $langSelect = $form->selectOption('language', [$current_lang])
                            ->addOption(t('Chose languages'), '')
                            ->addClass('form-control');

                        foreach($languages as $code => $lang) {
                            $langSelect->addOption($lang->getTitle(), $code);
                        }

                        $langSelect->display();
                    ?>
                </div>
            </div>

            <div class="submit">
                <!--
                <div class="remember">
                    <input type="checkbox" name="remember" class='icheck-me' data-skin="square" data-color="blue" id="remember">
                    <label for="remember">Remember me</label>
                </div>
                -->
                <input type="submit" value="<?php td("Sign me in") ?>" class='btn btn-primary'>
            </div>
        <?php $form->endForm(); ?>
        <div class="forget">
            <a href="javascript:void(0)" onclick="alert('Chia buồn, làm cóc có chức năng này');">
                <span><?php td("Forgot password") ?>?</span>
            </a>
        </div>
    </div>
</div>