<?php
/** @var Posts[] $posts */
/** @var Terms $cat */

$page_title = $cat->getName();
$this->document()->title = $page_title;
?>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Home') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        t($page_title)
    ),
)) ?>

<div class="fixCenter1K">
    <div id="news-list" class="row l656 fixCenter1K itemListView">
        <!-- Left -->
        <div class="col">
            <!-- Slide other news -->
            <div>
                <?php $this->widget('app.widget.OtherNews', array(
                    'parent_id' => $cat->getParent()->getId(),
                    'except' => $cat->getId()
                )); ?>
            </div>
            <!-- /slide other news -->

            <div id="all-news" class="clearfix">
                <?php  foreach($posts as $post) :
                        $excerpt = $post->getExcerpt();
                        if (!$excerpt) {
                            $excerpt = mb_substr(strip_tags($post->getContent(), '<br><span>'), 0, 140, 'UTF-8') .'...';
                        }
                    ?>
                <div class="news-item clearfix">
                    <div class="wrap-content">
                        <?php if ($post->getMainImg()) :?>
                        <a href="<?php echo $controller->createUrl('post/detail', array('id' => $post->getId())); ?>" class="thumb">
                            <img src="<?php echo $post->displayMainImg(); ?>" alt="<?php echo $post->getTitle(); ?>">
                        </a>
                        <?php endif; ?>
                        <h3 class="rs title" style="margin-top: 10px;">
                            <a href="<?php echo $controller->createUrl('post/detail', array('id' => $post->getId())); ?>">
                                <?php echo $post->getTitle(); ?>
                            </a>
                        </h3>
                        <p class="rs date" style="font-size: 11px; padding-top: 0"><?php echo $post->getCreatedTime()->format(t('d/m/Y')) ?></p>
                        <!--<p class="rs lead-news"><?php echo $excerpt; ?></p>-->
                        <!--<a class="view-detail" href="<?php echo $controller->createUrl('post/detail', array('id' => $post->getId())); ?>"><?php td('View more'); ?> <i class="icon iPickReadR"></i></a>-->
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

            <!-- Pagination -->
            <div class="news-paging">
                <?php
                $route = array();
                $route[0] = 'category/default';

                $this->widget('app.widget.FrontendPagination', array(
                    'pageSize' => $page_size,
                    'total' => $total,
                    'currentPage' => $this->request()->get('page', 'INT', 1),
                    'route' => $route,
                ));
                ?>
            </div>
        </div>
        <!--/left -->

        <!-- Right -->
        <div class="col">
            <?php $controller->block('news_cat.right'); ?>
        </div>
        <!--/right -->
    </div>
</div>