<?php /* @Consumer $consumer */ ?>
<form method="post" >
	<div class="column-left">
		<p>
			<label><b>NAME:</b></label>
			<input type="text" id="con_name" name="con_name" />
		</p>
		<p>
			<label><b>ALLOWED IPS:</b></label>
            <input type="text" id="allowed_ips" name="allowed_ips" />
		</p>
		<p>
			<label><b>DESCRIPTION:</b></label>
			<textarea  id="desc" name="desc" /></textarea>
		</p>
		<p>
			<label><b>STATUS:</b></label>
			<select name="status" id="status" "	>
				<option value="1" >ACTIVE</option>
				<option value="0" >INACTIVE</option>
			</select>
		</p>
		<p>
			<label><b>PUBLIC KEY:</b></label>
			<textarea id="public_key" name="public_key" ></textarea>
		</p>
	</div>
	<div class="clear"></div>
	<div class="action_bar">
		<input type="submit" name="submit" class="button blue" value="Submit Post" />
		<a href="#modal" class="modal button">Cancel</a>
	</div>
</form>