<form method="GET" >
	<div class="column-left">
        <div class="box-header">
            <h1>SEARCH CONSUMER</h1>
        </div>
        <p>
            <label><b>ID:</b></label>
            <input type="text" id="id" name="id" <?php if(isset($_GET['id'])) echo 'value="'.$_GET['id'].'"'; ?>	/>
        </p>
		<p>
			<label><b>NAME:</b></label>
            <input type="text" id="name" name="name" <?php if(isset($_GET['name'])) echo 'value="'.$_GET['name'].'"'; ?> />
		</p>
		<p>
			<label><b>ALLOWED IPS:</b></label>
			<input type="text" id="allowed_ips" name="allowed_ips" <?php if(isset($_GET['allowed_ips'])) echo 'value="'.$_GET['allowed_ips'].'"'; ?> />
		</p>
		<p>
			<label><b>DESCRIPTION:</b></label>
			<input type="text" id="desc" name="desc" <?php if(isset($_GET['desc'])) echo 'value="'.$_GET['desc'].'"'; ?> />
		</p>
		<p>
			<label><b>STATUS:</b></label>
			<select name="status" id="status" >
				<option value="1" <?php if(isset($_GET['status']) && $_GET['status']=='YES') echo 'selected="selected"' ?> >ACTIVE</option>
				<option value="0" <?php if(isset($_GET['status']) && $_GET['status']=='NO') echo 'selected="selected"' ?> >INACTIVE</option>
			</select>
		</p>
		<!--<p>
			<label><b>PUBLIC KEY:</b></label>
			<textarea id="public_key" name="public_key" <?php /*if(isset($_GET['public_key'])) echo 'value="'.$_GET['public_key'].'"'; */?> ></textarea>
		</p>-->
	</div>
	<div class="clear"></div>
	<div class="action_bar">
		<input type="submit" name="submit" class="button blue" value="Search" />
		<a href="#modal" class="modal button">Cancel</a>
	</div>
</form>
<div class="box">
	<div class="box-header">
		<h1>Consumer Manager</h1>
	</div>

	<table>
		<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Allowed_Ips</th>
			<th>Description</th>
			<th>Status</th>
		</tr>
		</thead>
        <tbody>

        <?php if(isset($consumers) && !empty($consumers)): ?>
            <?php foreach($consumers as $consumer): ?>
            <tr>
                <td><?php echo $consumer ['id'] ?></td>
                <td><?php echo $consumer['name'] ?></td>
                <td><?php echo $consumer['allowed_ips'] ?></td>
                <td><?php echo $consumer['desc'] ?></td>
                <td><?php echo $consumer['status'] ?></td>
                <td>
                    <a href="<?php echo $base_url.'consumer/edit?id='.$consumer['id']; ?>" class="button plain">Edit</a>
                </td>
            </tr>
                <?php endforeach; ?>
            <?php else: ?>
        <tr>
            <td><?php echo ' No result was found' ?></td>
        </tr>
            <?php endif; ?>

        </tbody>

	</table>
</div>
