<h3>Edit: # <?php echo $consumer->id ?></h3>
<br>
<br>

<form action="" method="post">
    <div class="column-left">
        <div class="box-header">
            <h1>EDIT CONSUMER</h1>
        </div>
        <p>
            <label><b>NAME:</b></label>
            <input type="text" id="name" name="con_name" value="<?php echo $consumer->name; ?>"/>
        </p>
        <p>
            <label><b>ALLOWED IPS:</b></label>
            <input type="text" id="allowed_ips" name="allowed_ips" value="<?php echo $consumer->allowed_ips; ?>" />
        </p>
        <p>
            <label><b>DESCRIPTION:</b></label>
            <input type="text" id="desc" name="desc" value="<?php echo $consumer->desc; ?>" />
        </p>
        <p>
            <label><b>PUBLIC KEY:</b></label>
            <textarea id="public_key" name="public_key"  ><?php echo $consumer->public_key; ?></textarea>
        </p>
    </div>
    <div class="clear"></div>
    <div class="action_bar">
        <input type="submit" name="submit" class="button blue" value="EDIT" />
    </div>


</form>