<?php
/** @var \Flywheel\View\Render $this */
/** @var Posts $post */
/** @var PostImages[] $postImages */
/** @var PostAttachments[] $postAttachments */

use Flywheel\Html\Form;
use Toxotes\Plugin;

$this->document()->addCss('css/jquery.fileupload-ui.css');
$this->document()->addJs('js/post.js');
$this->document()->addJs('js/plugins/file-upload/jquery.fileupload.js', 'TOP');

$form = new Form('post');
$form->setHtmlOption(array(
));
$taxonomy_label = Plugin::getTaxonomyOption($taxonomy, 'post', 'label');

$this->document()->title .= ($post->isNew()? t('Create new') : t('Edit')) .' ' .$taxonomy_label;

$taxonomy = $taxonomy || 'post';

if ($post->isNew()) {
    $main_img_url = $this->document()->getBaseUrl().'/img/no_img.png';
}

$mainImg = PostPeer::getPostMainImg($post->getId());
$postImages = PostPeer::getPostImg($post->getId());
?>
    <div class="page-header">
        <div class="pull-left">
            <h1><?php echo ($post->isNew()? t('Create new ' .$taxonomy_label) : t('Edit ' .$post->getTitle())); ?></h1>
        </div>
        <div class="pull-right">
            <ul class="minitiles">
                <li class="lime">
                    <a href="<?php echo $this->createUrl('post/default', array('taxonomy' => $taxonomy)) ?>"><i class="icon-th-list"></i></a>
                </li>
            </ul>
        </div>
    </div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        $taxonomy_label => array(
            'url' => array('post/default', array('taxonomy' => $taxonomy)),
        ),
        ($post->isNew()? t('Create New ' .$taxonomy_label) : t('Edit ' .$post->getTitle()))
    ),
)) ?>

<div id="post-frm">
<?php $form->beginForm(); ?>
<div class="row-fluid">
    <!-- Main input -->
    <div class="span8">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-edit"></i>
                    <?php echo t('Common information'); ?>
                </h3>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <input name="post[title]" value="<?php echo $post->getTitle() ?>" class="input-huge" id="post-title" placeholder="<?php echo t('Enter Title here') ?>">
                </div>

                <?php $this->widget('app.widget.SelectItemCategory', array(
                    'label' => t('Select Category'),
                    'taxonomy' => $taxonomy,
                    'selected' => $post->getTermId(),
                    'elementName' => 'term_parent',
                    'error' => isset($error['posts.term_id'])? $error['posts.term_id']: null,
                    'form' => $form,
                ));
                ?>

                <!-- editor -->

                <div class="control-group">
                    <?php $this->widget('app.widget.editor.TinyMCE', array(
                        'selector' => '#post-content',
                        'heigth' => 360
                    )); ?>
                    <textarea name="post[content]" id="post-content" class="input-block-level">
                        <?php echo ($post->getExcerpt()? $post->getExcerpt() .'<hr class="read-more-sep" />' : '');?>
                        <?php echo $post->getContent() ?>
                    </textarea>
                </div>
                <!-- /editor -->
            </div>
        </div>

        <!-- Post Images -->
        <?php if ('post' == $taxonomy || Plugin::getTaxonomyOption($taxonomy, 'post', 'enable_images', true)) :?>
        <div class="box">
            <div class="box-title">
                <h3><?php td('Post Images'); ?></h3>
            </div>
            <div class="box-content nopadding">
            <?php if (!empty($postImages)) :?>
                <ul class="gallery">
                <?php foreach ($postImages as $postImage) :?>
                <li>
                    <a href="#">
                        <img src="./../<?php echo $postImage->getPath()?>" width="200">
                    </a>
                    <div class="extras">
                        <div class="extras-inner">
                            <a href="<?php echo $this->createUrl('post_img/make_star', array('id' => $postImage->getId()))?>"><i class="icon-star"></i></a>
                            <a href="<?php echo $this->createUrl('post_img/edit', array('id' => $postImage->getId()))?>"><i class="icon-pencil"></i></a>
                            <a href="<?php echo $this->createUrl('post_img/remove', array('id' => $postImage->getId()))?>" class="tool-remove"><i class="icon-trash"></i></a>
                        </div>
                    </div>
                </li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>

                <!-- Upload tool -->
                <div class="row-fluid">
                    <div class="span3">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <div class="btn btn-danger fileinput-button"><i class="icon-cloud-upload"></i>
                                    <span><?php td('Upload new image'); ?></span>
                                    <input id="post-img-upload" type="file" name="upload_images" multiple="" data-post-id="<?php echo $post->getId(); ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="span9">
                        <br />
                        <div id="progress" class="progress progress-success">
                            <div class="bar"></div>
                        </div>
                    </div>
                </div>
                <!-- /upload tool -->
            </div>
        </div>
        <?php endif;?>
        <!-- /post images -->
    </div>
    <!-- /main input -->
    <div class="span4">
        <?php Plugin::doAction('custom_before' .$taxonomy .'_publish_box', $post, $form); ?>
        <div class="box box-bordered box-color">

            <div class="box-title"><h3><?php echo t('Publish'); ?></h3></div>
            <div class="box-content">
                <?php $this->widget('app.widget.SelectLanguage', array(
                    'selected' => $post->getLanguage(),
                    'elementName' => 'post[language]',
                    'form' => $form
                )) ?>

                <div class="control-group">
                    <label class="control-label"><?php echo t('Status'); ?></label>
                    <div class="controls">
                        <?php
                        $statusOpt = $form->selectOption('post[status]', $post->getStatus())
                                    ->addOption(t('Publish'), 'PUBLISH')
                                    ->addOption(t('Unpublish'), 'UNPUBLISH');

                        $statusOpt = Plugin::applyFilters('custom_' .$taxonomy .'_status_options', $statusOpt);
                        $statusOpt->display();
                        ?>
                    </div>
                </div>
                <div class="text-center">
                    <button name="submit" type="submit" class="btn btn-primary">
                        <i class="icon-save"></i>
                        <?php echo t('Save'); ?>
                    </button>
                </div>
            </div>
        </div>
        <?php Plugin::doAction('custom_after' .$taxonomy .'_publish_box', $post, $form); ?>

        <?php if ('post' == $taxonomy || Plugin::getTaxonomyOption($taxonomy, 'post', 'enable_attachments', true)) :?>
            <div class="box">
                <div class="box-title nopadding"><h3><?php echo t('Files attachment'); ?></h3></div>
                <div class="box-content nopadding">

                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<input name="post_id" value="<?php echo $post->getId()?>" type="hidden">
<?php $form->endForm(); ?>
</div>