<?php
/** @var \Flywheel\View\Render $this */
/** @var Items $item */

use Flywheel\Html\Form;
use Toxotes\Plugin;

$form = new Form('item');
$form->setHtmlOption(array(
    'class' => 'form-horizontal'
));
$taxonomy_label = Plugin::getTaxonomyOption($taxonomy, 'item', 'label');
?>

    <div class="page-header">
        <div class="pull-left">
            <h1><?php echo ($item->isNew()? t('Create New ' .$taxonomy_label) : t('Edit ' .$item->getTitle())); ?></h1>
        </div>
        <div class="pull-right">
            <ul class="minitiles">
                <li class="lime">
                    <a href="<?php echo $this->createUrl('post/default', array('taxonomy' => $taxonomy)) ?>"><i class="icon-th-list"></i></a>
                </li>
            </ul>
        </div>
    </div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        $taxonomy_label => array(
            'url' => array('post/default', array('taxonomy' => $taxonomy)),
        ),
        ($item->isNew()? t('Create New ' .$taxonomy_label) : t('Edit ' .$item->getTitle()))
    ),
)) ?>

<?php $form->beginForm(); ?>
<div class="row-fluid">
    <!-- Main input -->
    <div class="span8">
        <div class="box notitle">
            <div class="control-group">
                <input name="item[title]" value="<?php echo $item->getTitle() ?>" class="input-huge" id="item-title" placeholder="<?php echo t('Enter Title here') ?>">
            </div>

            <?php $this->widget('app.widget.SelectItemCategory', array(
                'label' => t('Select Category'),
                'taxonomy' => $taxonomy,
                'selected' => $item->getTermId(),
                'elementName' => 'term_parent',
                'error' => isset($error['items.term_id'])? $error['items.term_id']: null,
                'form' => $form,
            ));
            ?>
        </div>
    </div>
    <!-- /main input -->
    <div class="span4">

    </div>
</div>

<?php $form->endForm(); ?>