<?php
/** @var \Flywheel\View\Render $this */
/** @var Posts $item */

use Flywheel\Html\Form;
use Toxotes\Plugin;

$form = new Form('post');
$form->setHtmlOption(array(
));
$taxonomy_label = Plugin::getTaxonomyOption($taxonomy, 'post', 'label');

$this->document()->title .= ($post->isNew()? t('Create new') : t('Edit')) .' ' .$taxonomy_label;

$taxonomy = $taxonomy || 'post';
?>

    <div class="page-header">
        <div class="pull-left">
            <h1><?php echo ($post->isNew()? t('Create new ' .$taxonomy_label) : t('Edit ' .$post->getTitle())); ?></h1>
        </div>
        <div class="pull-right">
            <ul class="minitiles">
                <li class="lime">
                    <a href="<?php echo $this->createUrl('post/default', array('taxonomy' => $taxonomy)) ?>"><i class="icon-th-list"></i></a>
                </li>
            </ul>
        </div>
    </div>

<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Dashboard') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        $taxonomy_label => array(
            'url' => array('post/default', array('taxonomy' => $taxonomy)),
        ),
        ($post->isNew()? t('Create New ' .$taxonomy_label) : t('Edit ' .$post->getTitle()))
    ),
)) ?>

<?php $form->beginForm(); ?>
<div class="row-fluid">
    <!-- Main input -->
    <div class="span8">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-edit"></i>
                    <?php echo t('Common information'); ?>
                </h3>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <input name="post[title]" value="<?php echo $post->getTitle() ?>" class="input-huge" id="post-title" placeholder="<?php echo t('Enter Title here') ?>">
                </div>

                <?php $this->widget('app.widget.SelectItemCategory', array(
                    'label' => t('Select Category'),
                    'taxonomy' => $taxonomy,
                    'selected' => $post->getTermId(),
                    'elementName' => 'term_parent',
                    'error' => isset($error['posts.term_id'])? $error['posts.term_id']: null,
                    'form' => $form,
                ));
                ?>

                <!-- editor -->

                <div class="control-group">
                    <?php $this->widget('app.widget.editor.TinyMCE', array(
                        'selector' => '#post-content',
                        'heigth' => 360
                    )); ?>
                    <textarea name="post[content]" id="post-content" class="input-block-level">
                        <?php echo ($post->getExcerpt()? $post->getExcerpt() .'<hr class="read-more-sep" />' : '');?>
                        <?php echo $post->getContent() ?>
                    </textarea>
                </div>
                <!-- /editor -->
            </div>
        </div>
    </div>
    <!-- /main input -->
    <div class="span4">
        <?php Plugin::doAction('custom_before' .$taxonomy .'_publish_box', $post, $form); ?>
        <div class="box box-bordered box-color">

            <div class="box-title"><h3><?php echo t('Publish'); ?></h3></div>
            <div class="box-content">
                <?php $this->widget('app.widget.SelectLanguage', array(
                    'selected' => $post->getLanguage(),
                    'elementName' => 'post[language]',
                    'form' => $form
                )) ?>

                <div class="control-group">
                    <label class="control-label"><?php echo t('Status'); ?></label>
                    <div class="controls">
                        <?php
                        $statusOpt = $form->selectOption('post[status]', $post->getStatus())
                                    ->addOption(t('Publish'), 'PUBLISH')
                                    ->addOption(t('Unpublish'), 'UNPUBLISH');

                        $statusOpt = Plugin::applyFilters('custom_' .$taxonomy .'_status_options', $statusOpt);
                        $statusOpt->display();
                        ?>
                    </div>
                </div>
                <div class="text-center">
                    <button name="submit" type="submit" class="btn btn-primary">
                        <i class="icon-save"></i>
                        <?php echo t('Save'); ?>
                    </button>
                </div>
            </div>
        </div>
        <?php Plugin::doAction('custom_after' .$taxonomy .'_publish_box', $post, $form); ?>

        <?php if ('post' == $taxonomy || Plugin::getTaxonomyOption($taxonomy, 'post', 'enable_images', true)) :?>
        <div class="box">
            <div class="box-title"><h3><?php echo t('Images'); ?></h3></div>
            <div class="box-content">

            </div>
        </div>
        <?php endif; ?>

        <?php if ('post' == $taxonomy || Plugin::getTaxonomyOption($taxonomy, 'post', 'enable_attachments', true)) :?>
            <div class="box">
                <div class="box-title"><h3><?php echo t('Files attachment'); ?></h3></div>
                <div class="box-content">

                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php $form->endForm(); ?>