<?php
/** @var \Flywheel\Document\Html $document */
$document = $this->document();
?>
<!DOCTYPE html>
<html>
<head>
    <title><?php echo $document->title ;?></title>
    <base href="<?php echo $document->getBaseUrl(); ?>">
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="assets/css/style.css">
    <!--[if lte IE 7]>
    <link rel="stylesheet" type="text/css" href="assets/css/ie7.css">
    <![endif]-->
    <script type="text/javascript" src="assets/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery.tinycarousel.js"></script>
    <script type="text/javascript" src="assets/js/script.js"></script>
    <?php
    echo $document->css();
    echo $document->js('TOP');
    ?>
</head>
<body>

<div class="main-layout">
    <!-- Header -->
    <div id="header" class="clearfix">
        <h1 class="rs">
            <a href="#">
                <img src="assets/images/logo.png" alt="<?php echo $setting['site_name'] ?>">
            </a>
        </h1>
        <div class="right-panel">
            <div class="clearfix">
                <?php if ($controller->currentLang) : ?>
                <div class="language">
                    <div class="current-lang">
                        <img src="assets/images/<?php echo $controller->currentLang->getImage() ?>.png" alt="<?php echo $controller->currentLang->getTitle() ?>">
                        <span><?php echo $controller->currentLang->getTitle() ?></span>
                        <i class="icon iPickDownW"></i>
                    </div>

                    <ul id="sys-lst-language" class="rs">
                    <?php foreach ($controller->languages as $lang) :?>
                        <li><a href="<?php echo $controller->makeLangUrl($lang->getLangCode()) ?>">
                                <img src="assets/images/<?php echo $lang->getImage(); ?>.png" alt="<?php echo $lang->getTitle(); ?>">
                                <span><?php echo $lang->getTitle(); ?></span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                    </ul>

                </div>
                <?php endif; ?>

                <!--
                <div class="sign-in">
                    <a href="#">Sign in</a>
                    <span class="sep">|</span>
                    <a href="#">Sign out</a>
                </div>
                -->
            </div>
            <h3 class="rs small-logo">
                <img src="assets/images/logo-small.png" alt="#SITE_NAME">
            </h3>
        </div>
    </div>
    <!-- /header -->
</div>

<div id="main-menu">
    <?php $controller->block('main_menu'); ?>
</div>

<?php echo $buffer ?>

<div id="footer">
    <div class="fixCenter1K">
        <div class="top-thumb">
            <a href="http://www.nimh.gov.vn/" target="_blank">
                <img src="./media/images/th-logo.png" alt="" height="50" style=" margin-right: 180px; ">
            </a>
            <a href="http://www.samhsa.gov/index.aspx" target="_blank">
                <img src="./media/images/th-227x50-1.png" alt="" style=" margin-right: 150px; ">
            </a>
            <img src="./media/images/th-227x50.png" alt="" style=" margin-right: 190px; ">
            <a href="http://uclaisap.org" target="_blank">
                <img src="./media/images/th-227x50-2.png" alt="">
            </a>
        </div>
        <div class="clearfix">
            <div class="col-type1">
                <div class="wrap-foot-item">

                    <h5 class="rs title">VH - ATTC</h5>
                    <?php $controller->block('footer.menu'); ?>

                </div>
            </div><!--end: col-type1 -->
            <div class="col-type1">
                <div class="wrap-foot-item">
                    <h5 class="rs title">Quick link</h5>

                    <ul class="weblinks rs">
                        <li>
                            <a href="http://www.hmu.edu.vn/news/default.asp" target="_blank" rel="no follow">Hanoi Medical University</a>	<!---->

                            <!---->
                        </li>
                        <li>
                            <a href="http://www.pepfar.gov/" target="_blank" rel="no follow">The U.S. President's Emergency Plan for AIDS Relief</a>	<!---->

                            <!---->
                        </li>
                        <li>
                            <a href="http://vietnam.usembassy.gov/cdc.html" target="_blank" rel="no follow">Embassy of the United States</a>	<!---->

                            <!---->
                        </li>
                        <li>
                            <a href="http://uclaisap.org/vhattc/" target="_blank" rel="no follow">VHATTC: Vietnam HIV Addiction Technology Transfer Center Network</a>	<!---->

                            <!---->
                        </li>
                        <li>
                            <a href="http://www.nimh.gov.vn/" target="_blank" rel="no follow">National Institute of Metal Health</a>	<!---->

                            <!---->
                        </li>
                    </ul>

                </div>
            </div><!--end: col-type1 -->
            <div class="col-type1">
                <div class="wrap-foot-item">
                    <h5 class="rs title">Liên hệ</h5>
                    <p class="rs desc-contact">
                        <!-- Vietnam HIV Addiction Technology Transfer Center
                        Center for Research and Training on HIV/AIDS -->
                        Room 522, A1 Building, Hanoi Medical University, No. 1A Ton That Tung Street, Dong Da Dist, Hanoi, Vietnam
                    </p>

                    <p class="rs item-info">
                        <span class="lbl">TEL:</span>
                        <span class="val">(+844)35741596</span>
                    </p>

                    <p class="rs item-info">
                        <span class="lbl">FAX:</span>
                        <span class="val">(+844)35741596</span>
                    </p>
                    <p class="rs item-info">
                        <span class="lbl">Email:</span>
                        <a href="mailto:creata@hmu.edu.vn" class="val fc-w">creata@hmu.edu.vn</a>
                    </p>
                </div>
            </div><!--end: col-type1 -->
            <div class="col-type2">
                <div class="wrap-foot-item">
                    <h5 class="rs title">Facebook</h5>
                    <div class="social-contact">
                        <a href="https://www.facebook.com/vhattc" target="_blank">
                            <i class="icon iFb"></i>
                        </a>
                        <!--<a href="#">
                            <i class="icon iTw"></i>
                        </a>-->
                    </div>
                    <!--<h5 class="rs title">Email to Subcrible</h5>
                    <form class="email-subcrible clearfix" name="email">
                        <label for="email-subcrible">
                            <input type="text" id="email-subcrible" placeholder="Your email">
                            <i class="icon iPickRightW"></i>
                        </label>
                        <input type="submit" value="Send">
                    </form>
                    -->
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $document->js('BOTTOM'); ?>
</body>
</html>