<?php $doc = \Flywheel\Factory::getDocument();
?>
<div id="login_container">
    <div id="login_form">
        <form method="post" action="<?php echo $action ?>">
            <p>
                <input type="text" id="email" name="email" placeholder="Email" class="{validate: {required: true}}" />
            </p>
            <p>
                <input type="password" id="password" name="password" placeholder="Password" class="{validate: {required: true}}" />
            </p>
            <button type="submit" class="button blue"><span class="glyph key"></span> Login</button>
        </form>
    </div>
</div>

