<div class="row-fluid">
    <div class="span4 offset4">
        <div class="widget">
            <div class="page-header">
                <div class="page-title">
                    <h1>LOGIN</h1>
                    <span>This area only allow administrator users</span>
                </div>
            </div>

            <div class="well">
                <form class="form-horizontal" action="" method="POST">
                    <?php if (isset($error) && !empty($error)) :?>
                    <div class="alert alert-error margin">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <?php echo implode('<br>',$error) ?>
                    </div>
                    <?php endif; ?>

                    <div class="control-group">
                        <label class="control-label" for="credential">Credential: </label>
                        <div class="controls">
                            <input type="text" name="credential" value="<?php echo $credential; ?>" class="span12" placeholder="Email or Username">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Password:</label>
                        <div class="controls">
                            <input type="password" name="password" class="span12" placeholder="Password"></div>
                    </div>

                    <div class="form-actions align-right">
                        <button type="submit" class="btn btn-primary">Sign in</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>