<div class="crumbs">
    <ul id="breadcrumbs" class="breadcrumb">
        <?php foreach ($activesLink as $activeLink) : ?>
        <li><a href="<?php echo $activeLink['url'] ?>"><?php echo $activeLink['label'] ?></a></li>
        <?php endforeach; ?>

        <?php foreach ($inActivesLink as $inActiveLink) : ?>
            <li class="active"><a><?php echo $inActiveLink ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>