<?php
/** @var \Flywheel\View\Render $this */
?>
<div id="sidebar">

    <div class="sidebar-tabs">
        <div id="general">
            <!-- Sidebar user
            <div class="sidebar-user widget">
                <div class="navbar"><div class="navbar-inner"><h6>Wazzup, Eugene!</h6></div></div>
                <a href="#" title="" class="user"><img src="img/demo/sidebar_user_big.png" alt="" /></a>
                <ul class="user-links">
                    <li><a href="#" title="">New users<strong>+12</strong></a></li>
                    <li><a href="#" title="">New orders<strong>+156</strong></a></li>
                    <li><a href="#" title="">New messages<strong>+45</strong></a></li>
                </ul>
            </div>
            <!-- /sidebar user -->

            <!-- General stats
            <div class="general-stats widget">
                <ul class="head">
                    <li><span>Users</span></li>
                    <li><span>Orders</span></li>
                    <li><span>Visits</span></li>
                </ul>
                <ul class="body">
                    <li><strong>116k+</strong></li>
                    <li><strong>1290</strong></li>
                    <li><strong>554</strong></li>
                </ul>
            </div>

            <!-- Main navigation -->
            <ul class="navigation widget">
                <?php for ($i = 0, $size = sizeof($items); $i < $size; ++$i) : ?>
                    <li<?php if ($items[$i]['active']):?> class="active"<?php endif; ?>>
                        <a href="<?php echo $items[$i]['url'] ?>"<?php if ($items[$i]['active']):?> id="current"<?php endif; ?>>
                            <?php echo $items[$i]['label'] ?>
                        </a>

                        <?php if (isset($items[$i]['items'])): ?>
                            <ul>
                                <?php for($j = 0, $sizeOfSub = sizeof($items[$i]['items']); $j < $sizeOfSub; ++$j) :?>
                                    <li>
                                        <a href="<?php echo $items[$i]['items'][$j]['url'] ?>"<?php if ($items[$i]['items'][$j]['active']):?> class="current"<?php endif; ?>>
                                            <?php echo $items[$i]['items'][$j]['label'] ?>
                                        </a>
                                    </li>
                                <?php endfor; ?>
                            </ul>
                        <?php endif; ?>
                    </li>
                <?php endfor; ?>
            </ul>
            <!-- /main navigation -->

        </div>

    </div>
</div>
