<?php

/** @var Flywheel\Document\Html $document  */
$document = $this->document();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?php echo $document->getBaseUrl() ?>">
        <style type="text/css">@media print {  .gmnoprint {    display:none  }}@media screen {  .gmnoscreen {    display:none  }}</style>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <title><?php echo $document->title ?></title>
        <link href="<?php echo $document->getPublicPath() ?>/css/bootstrap.css" rel="stylesheet" type="text/css">
        <!--[if IE 8]><link href="<?php echo $document->getPublicPath() ?>/css/ie8.css" rel="stylesheet" type="text/css" /><![endif]-->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet" type="text/css">

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&amp;sensor=false"></script><script src="http://maps.gstatic.com/intl/en_us/mapfiles/api-3/12/8a/main.js" type="text/javascript"></script>

        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/charts/excanvas.min.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/charts/jquery.flot.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/charts/jquery.flot.resize.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/charts/jquery.sparkline.min.js"></script>

        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/ui/jquery.easytabs.min.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/ui/jquery.collapsible.min.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/ui/prettify.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/ui/jquery.colorpicker.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/ui/jquery.timepicker.min.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/ui/jquery.fancybox.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/ui/jquery.fullcalendar.min.js"></script>

        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/forms/jquery.uniform.min.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/forms/jquery.tagsinput.min.js"></script>

        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/plugins/tables/jquery.dataTables.min.js"></script>

        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/files/bootstrap.min.js"></script>

        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/functions/index.js"></script>

        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/charts/graph.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/charts/chart1.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/charts/chart2.js"></script>
        <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>/js/charts/chart3.js"></script>

        <style type="text/css">.jqstooltip { position: absolute;left: 0px;top: 0px;visibility: hidden;background: rgb(0, 0, 0) transparent;background-color: rgba(0,0,0,0.6);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";color: white;font: 10px arial, san serif;text-align: left;white-space: nowrap;padding: 5px;border: 1px solid white;z-index: 10000;}.jqsfield { color: white;font: 10px arial, san serif;text-align: left;}</style>
    </head>
	
	<body>
    <!-- Fixed top -->
    <?php $this->widget('app.widget.BackendTopBar'); ?>
    <!-- /fixed top -->

    <!-- Content container -->
    <div id="container">
        <!-- Sidebar -->
        <?php $this->widget('app.widget.BackendSideBar'); ?>
        <!-- /sidebar -->

        <!-- Content -->
        <div id="content">

            <!-- Content wrapper -->
            <div class="wrapper">
                <?php echo $controller; ?>
            </div>
            <!-- /content wrapper -->
        </div>
        <!-- /content -->

    </div>
    <!-- /content container -->

    <!-- Footer -->
    <div id="footer">
        <div class="copyrights">&copy; by Lưu Trọng Hiếu 2013.</div>
        <ul class="footer-links">
            <li><a href="mailto:tronghieu.luu@gmail.com?Subject=Contact%20from%20toxotes%20admin" title=""><i class="icon-cogs"></i><?php echo t('Contact admin'); ?></a></li>
            <!--<li><a href="#" title=""><i class="icon-screenshot"></i>Report bug</a></li>-->
        </ul>
    </div>
    <!-- /footer -->

    </body>
</html>