<!DOCTYPE html>
<?php $document = \Flywheel\Factory::getDocument();?>
<html lang="en">
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8"><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8" />
    <base href="<?php echo $document->getBaseUrl() ?>">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <!--<meta name="viewport" content="user-scalable=no" />-->

    <title>LOGIN</title>

    <!-- Stylesheets -->
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/reset.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/icons.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/formalize.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/checkboxes.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/sourcerer.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/jqueryui.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/tipsy.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/calendar.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/tags.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/fonts.css" />
    <link rel="stylesheet" href="<?php echo $document->getBaseUrl(); ?>assets/css/main.css" />
    <link rel="stylesheet" media="all and (orientation:portrait)" href="<?php echo $document->getBaseUrl(); ?>assets/css/portrait.css" />
    <link rel="apple-touch-icon" href="<?php echo $document->getBaseUrl(); ?>apple-touch-icon-precomposed.png" />
    <link rel="shortcut icon" href="<?php echo $document->getBaseUrl(); ?>favicon.ico" type="image/x-icon" />

    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body id="login">
<?php
echo $document->getComponentData();?>

<!-- FOUNDATION JAVASCRIPT -->
<script>
    document.write('<script src=' +
            ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
            '.js><\/script>')
</script>
<!-- JavaScript -->
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.min.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jqueryui.min.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.cookies.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.pjax.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/formalize.min.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.metadata.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.validate.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.checkboxes.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.selectskin.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.fileinput.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.datatables.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.sourcerer.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.tipsy.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.calendar.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.inputtags.min.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.wymeditor.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.livequery.js"></script>
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/jquery.highcharts.js"></script>

<!-- Just examples, can be removed in production -->
<script src="<?php echo $document->getBaseUrl(); ?>assets/js/chart_examples.js"></script>

<script src="<?php echo $document->getBaseUrl(); ?>assets/js/application.js"></script>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-11172759-15']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>
</body>
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8"><!-- /Added by HTTrack -->
</html>