<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo $this->document()->getBaseUrl() ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title>Pannonia - premium responsive admin template by Eugene Kopyov</title>
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css" />
    <!--[if IE 8]><link href="css/ie8.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 9]><link href="css/ie9.css" rel="stylesheet" type="text/css" /><![endif]-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>

    <script type="text/javascript" src="js/plugins/charts/jquery.sparkline.min.js"></script>

    <script type="text/javascript" src="js/files/bootstrap.min.js"></script>

    <script type="text/javascript" src="js/functions/error.js"></script>

</head>

<body class="no-background">

<!-- Fixed top -->
<div id="top">
    <div class="fixed">
        <a href="<?php echo $this->document()->getBaseUrl() ?>" title="" class="logo"><img src="img/logo.png" alt="" /></a>
    </div>
</div>
<!-- /fixed top -->

<div id="container">
<?php echo $controller; ?>
</div>


<!-- Footer -->
<div id="footer">
    <div class="copyrights">&copy; 2013 by Flywheel Team.</div>
</div>
<!-- /footer -->

</body>
</html>
