<div class="fixCenter1K">
    <div id="main-slider-code">
        <a href="#" class="buttons prev">left</a>
        <div class="viewport">
            <ul class="overview rs">
                <li><img src="assets/images/ex/th-1000x370.png"/></li>
                <li><img src="assets/images/ex/th-1000x370-1.png" /></li>
                <li><img src="assets/images/ex/th-1000x370-2.png" /></li>
                <li><img src="assets/images/ex/th-1000x370-3.png" /></li>
                <li><img src="assets/images/ex/th-1000x370-4.png" /></li>
            </ul>
        </div>
        <a href="#" class="buttons next">right</a>

        <div class="wrap-pager">
            <span class="mack"></span>
            <ul class="pager rs">
                <li><a rel="0" class="pagenum" href="#">1</a></li>
                <li><a rel="1" class="pagenum" href="#">2</a></li>
                <li><a rel="2" class="pagenum" href="#">3</a></li>
                <li><a rel="3" class="pagenum" href="#">4</a></li>
                <li><a rel="4" class="pagenum" href="#">5</a></li>
            </ul>
        </div>
    </div>
</div>