<?php /** @var SlideShow $widget */ ?>
<div class="fixCenter1K">
    <div id="main-slider-code">
        <?php if (!empty($widget->banners)) : ?>
        <a href="#" class="buttons prev">left</a>
        <div class="viewport">
            <ul class="overview rs">
            <?php foreach($widget->banners as $banner) :?>
                <li><img src="<?php echo $this->document()->getBaseUrl() . $banner->getFile(); ?>"></li>
            <?php endforeach; ?>
            </ul>
        </div>
        <a href="#" class="buttons next">right</a>

        <div class="wrap-pager">
            <span class="mack"></span>
            <ul class="pager rs">
                <?php
                $i = 0;
                foreach($widget->banners as $banner) :
                    $i++
                ?>
                    <li><a rel="<?php echo $i-1 ?>" class="pagenum" href="#"><?php echo $i ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
    </div>
</div>