<?php
use Toxotes\Cms;
/** @var \SlideShow $widget */
?>
<div class="fixCenter1K">
    <?php if (!empty($widget->banners)) :?>
    <div class="block">
        <h3 class="title"><?php Cms::td('Partner organizations'); ?></h3>
        <div class="block-content">
            <div id="slider_partner">
                <a class="buttons prev disable" href="#">
                    <i class="iconB iPrev"></i>
                </a>
                <a class="buttons next" href="#">
                    <i class="iconB iNext"></i>
                </a>
                <div class="viewport">
                    <ul class="rs overview clearfix">
                        <?php foreach ($widget->banners as $banner) :?>
                            <li>
                                <div class="partner-item">
                                    <div class="center-thumb">
                                        <span class="vertical-hold"><!--for IE6,7--></span>
                                        <a href="<?php echo $banner->getLink(); ?>" target="<?php echo $banner->getLinkTarget() ?>" class="thumb">
                                            <img src="<?php echo $this->document()->getBaseUrl() .$banner->getFile()?>" alt="<?php echo $banner->getTitle() ;?>">
                                        </a>
                                    </div>
                                    <p class="rs name"><?php echo $banner->getTitle() ;?></p>
                                </div>
                            </li>

                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <!--end: ...-->
    </div>
    <?php endif; ?>
</div>