<?php
/** @var Flywheel\Document\Html $document  */
$document = $this->document();
?>
<!DOCTYPE html>
<html>
<head>
    <base href="<?php echo $document->getBaseUrl(); ?>">
    <meta charset="utf8">
    <title><?php echo $document->title ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Apple devices fullscreen -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <!-- Apple devices fullscreen -->
    <meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />


    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- Bootstrap responsive -->
    <link rel="stylesheet" href="css/bootstrap-responsive.min.css">
    <!-- jQuery UI -->
    <link rel="stylesheet" href="css/plugins/jquery-ui/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="css/plugins/jquery-ui/smoothness/jquery.ui.theme.css">
    <!-- PageGuide -->
    <link rel="stylesheet" href="css/plugins/pageguide/pageguide.css">
    <!-- Fullcalendar -->
    <link rel="stylesheet" href="css/plugins/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="css/plugins/fullcalendar/fullcalendar.print.css" media="print">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/custom.css">
    <!-- Color CSS -->
    <!--<link rel="stylesheet" href="css/themes.css">-->


    <!-- jQuery -->
    <script src="js/jquery.min.js"></script>
    <!-- jQuery UI -->
    <script src="js/plugins/jquery-ui/jquery.ui.core.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.widget.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.mouse.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.draggable.min.js"></script>
    <script src="js/plugins/jquery-ui/jquery.ui.resizable.min.js"></script>
    <!-- Touch enable for jquery UI -->
    <script src="js/plugins/touch-punch/jquery.touch-punch.min.js"></script>
    <!-- slimScroll -->
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <!-- Bootstrap -->
    <script src="js/bootstrap.min.js"></script>
    <!-- vmap -->
    <script src="js/plugins/vmap/jquery.vmap.min.js"></script>
    <script src="js/plugins/vmap/jquery.vmap.world.js"></script>
    <script src="js/plugins/vmap/jquery.vmap.sampledata.js"></script>
    <!-- Bootbox -->
    <script src="js/plugins/bootbox/jquery.bootbox.js"></script>
    <!-- Flot -->
    <script src="js/plugins/flot/jquery.flot.min.js"></script>
    <script src="js/plugins/flot/jquery.flot.bar.order.min.js"></script>
    <script src="js/plugins/flot/jquery.flot.pie.min.js"></script>
    <script src="js/plugins/flot/jquery.flot.resize.min.js"></script>
    <!-- imagesLoaded -->
    <script src="js/plugins/imagesLoaded/jquery.imagesloaded.min.js"></script>
    <!-- PageGuide -->
    <script src="js/plugins/pageguide/jquery.pageguide.js"></script>
    <!-- FullCalendar -->
    <script src="js/plugins/fullcalendar/fullcalendar.min.js"></script>

    <!-- Theme framework -->
    <script src="js/eakroko.min.js"></script>
    <!-- Theme scripts -->
    <script src="js/application.min.js"></script>
    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico" />
    <!-- Apple devices Homescreen icon -->
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png" />
    <?php
    echo $document->css();
    echo $document->js('TOP');
    ?>
    <script type="text/javascript">
        var base_url = "<?php echo $document->getBaseUrl(); ?>";
    </script>
</head>

	<body>
    <!-- Fixed top -->
    <?php $this->widget('app.widget.BackendTopBar'); ?>
    <!-- /fixed top -->

    <!-- Content container -->
    <div id="content" class="container-fluid">
        <!-- Sidebar -->
        <?php $this->widget('app.widget.BackendSideBar'); ?>
        <!-- /sidebar -->

        <!-- Content -->
        <div id="main">

            <!-- Content wrapper -->
            <div class="container-fluid">
                <?php echo $buffer; ?>
            </div>
            <!-- /content wrapper -->
        </div>
        <!-- /content -->

    </div>
    <!-- /content container -->

    <!-- Loading -->
    <div id="loading-box">
        <div id="loading-box-content">
            <strong><?php echo t('Loading ...') ?></strong>
        </div>
    </div>
    <!-- /loading -->

    <script type="text/javascript" src="<?php echo $document->getPublicPath() ?>js/common.js"></script>
    <?php echo $document->js('BOTTOM'); ?>
    </body>
</html>