<h3>Tạo mới tài khoản</h3>
<br>
<br>

<form action="" method="post">
<table>
	<tbody>
		<tr>
			<td width="200px">Name</td>
			<td>
				<input type="text" name="name" id="name">
			</td>
		</tr>
		<tr>
			<td width="200px">Currency</td>
			<td>
				<select name="currency" id="currency" placeholder="Currency"	>
					<option value="VND" >VND</option>
					<option value="USD" >FROZEN</option>
					<option value="CNY" >DELETE</option>
				</select>
			</td>
		</tr>

		<tr>
			<td width="200px">Status</td>
			<td>
				<select name="status" id="status" placeholder="Status"	>
					<option value="NORMAL">NORMAL</option>
					<option value="FROZEN" >FROZEN</option>
					<option value="DELETE" >DELETE</option>
				</select>
			</td>
		</tr>
		<tr>
			<td width="200px">Type</td>
			<td>
				<select name="type" id="type" placeholder="Type"	>
					<option value="NORMAL">NORMAL</option>
					<option value="SYSTEM" >FROZEN</option>
					<option value="FEE" >DELETE</option>
					<option value="FEE" >DELETE</option>
				</select>
			</td>
		</tr>
	</tbody>
</table>

<br>
<br>
<button type="submit" name="submit">Create</button>
<a href="#">Cancel</a>

</form>