<h3>Account: # <?php echo $account->id ?></h3>
<br>
<br>

<table>
	<tbody>
		<tr>
			<td width="200px">ID</td>
			<td><?php echo $account->id; ?></td>
		</tr>
		<tr>
			<td width="200px">UK</td>
			<td><?php echo $account->uk; ?></td>
		</tr>
		<tr>
			<td width="200px">Name</td>
			<td><?php echo $account->name; ?></td>
		</tr>
		<tr>
			<td width="200px">Version</td>
			<td><?php echo $account->version; ?></td>
		</tr>
		<tr>
			<td width="200px">Currency</td>
			<td><?php echo $account->currency; ?></td>
		</tr>
		<tr>
			<td width="200px">Balance</td>
			<td><?php echo $account->balance; ?></td>
		</tr>
		<tr>
			<td width="200px">Frozen_balance</td>
			<td><?php echo $account->frozen_balance; ?></td>
		</tr>
		<tr>
			<td width="200px">Status</td>
			<td><?php echo $account->status; ?></td>
		</tr>
		<tr>
			<td width="200px">Type</td>
			<td><?php echo $account->type; ?></td>
		</tr>
		<tr>
			<td width="200px">CRC</td>
			<td><?php echo $account->crc; ?></td>
		</tr>
		<tr>
			<td width="200px">Created time</td>
			<td><?php echo $account->created_time; ?></td>
		</tr>
		<tr>
			<td width="200px">Last modified time</td>
			<td><?php echo $account->modified_time; ?></td>
		</tr>
	</tbody>
</table>