<?php
/** @var Posts $post */
?>
<div id="about-page" class="row l260 faux-left-gray fixCenter1K">
    <div class="col col-type1">
        <?php $controller->block('about_us.menu'); ?>
    </div>

    <div class="col col-type2">
        <div class="text-content">
            <div class="item-page">
                <h2><?php echo $post->getTitle(); ?></h2>
                <?php if ($post->getMainImg()): ?>
                    <img src="./<?php echo $post->displayMainImg(); ?>" alt="<?php echo $post->getTitle();?>" class="article-img">
                <?php endif; ?>
                <?php if ($post->getExcerpt()): ?>
                    <p>
                        <?php echo $post->getExcerpt(); ?>
                    </p>
                <?php endif; ?>
                <?php echo $post->getContent(); ?>
            </div>
        </div>
    </div>
</div>

<div id="slide-partner-org">
    <?php $controller->block('partners_list'); ?>
</div>