<?php
/** @var \Terms $term */
/** @var \Posts $post */
$page_title = $post->getTitle();
$this->document()->title .= $page_title;

$link = $controller->createUrl('post/detail', array('id' => $post->getId()));
?>
<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Home') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        $term->getName() => array(
            'url' => $controller->createUrl('category/default', array('id' => $term->getId()))
        ),
        ($page_title)
    ),
)) ?>

<div id="article-detail" class="row l656 fixCenter1K">
    <div class="col">
        <div class="art-full-info">
            <?php if ($post->getMainImg()) : ?>
            <img class="desc-img" src="<?php echo $post->displayMainImg('656x305'); ?>" alt="<?php echo $post->getTitle(); ?>">
            <?php endif; ?>
            <h2 class="rs art-title"><?php echo $post->getTitle(); ?></h2>
            <div class="art-ultility clearfix">
                <div class="date-created">
                    <span><?php echo $post->getCreatedTime()->format('d/m/Y'); ?></span>
                    <!--<span class="sep">|</span>
                    <span>written by super user</span>-->
                </div>
                <div class="art-tool">
                        <span class="like-fb">
                            <iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $link; ?>&amp;layout=button_count&amp;show_faces=false&amp;width=450&amp;action=like&amp;font&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:74px; height:20px;" allowtransparency="true"></iframe>
                        </span>
                    <span class="sep"></span>
                        <span>
                            <i class="icon iEmail"></i>
                            Email
                        </span>
                    <span class="sep"></span>
                        <span>
                            <i class="icon iPrinter"></i>
                            Print
                        </span>
                </div>
            </div>

            <div class="text-content">
                <?php if ($post->getExcerpt()) :?>
                <p>
                    <strong><?php echo $post->getExcerpt(); ?></strong>
                </p>
                <?php endif; ?>
                <p><?php echo $post->getContent(); ?></p>
            </div>

            <!-- Facebook comment -->
            <div class="art-comment">
            </div>
            <!--/facebook comment -->
            <?php
            $siblings = $term->getSiblings();
            foreach ($siblings as $s) {
                $ids[] = $s->getId();
            }
            $ids[] = $term->getId();

            $top_hits = Posts::read()->where('status = :status AND `id` !=' .$post->getId())
                ->setParameter(':status', 'PUBLISH', \PDO::PARAM_STR)
                ->andWhere('`term_id` IN (' .implode(',', $ids) .')')
                ->orderBy('hits', 'DESC')
                ->setMaxResults(5)
                ->execute()
                ->fetchAll(\PDO::FETCH_CLASS, Posts::getPhpName(), array(null, false));

            $latest_news = Posts::read()->where('status = :status AND `id` !=' .$post->getId())
                ->setParameter(':status', 'PUBLISH', \PDO::PARAM_STR)
                ->andWhere('`term_id` IN (' .implode(',', $ids) .')')
                ->orderBy('created_time', 'DESC')
                ->setMaxResults(5)
                ->execute()
                ->fetchAll(\PDO::FETCH_CLASS, Posts::getPhpName(), array(null, false));

            ?>

            <div class="row c3">
                <div class="col">
                    <?php if ($top_hits) :?>
                    <div class="block relation-articles">
                        <h3 class="title"><?php td('Top Hits'); ?></h3>
                        <div class="block-content">
                            <ul class="rs">
                                <?php foreach($top_hits as $p) :?>
                                    <?php $title = (mb_strlen($p->getTitle()) > 72)? mb_substr($p->getTitle(), 0, 72) .'...': $p->getTitle();?>
                                    <li>
                                        <a href="<?php echo $controller->createUrl('post/detail', array('id' => $p->getId())); ?>">
                                            <?php echo $title ?>
                                        </a>
                                        <span class="fc-g fs11"> -  <?php echo $p->getCreatedTime()->format('d/m/Y') ;?></span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
                <div class="col">

                    <?php if ($top_hits) :?>
                        <div class="block relation-articles">
                            <h3 class="title"><?php td('Latest News'); ?></h3>
                            <div class="block-content">
                                <ul class="rs">
                                    <?php foreach($latest_news as $p) :?>
                                        <?php $title = (mb_strlen($p->getTitle()) > 72)? mb_substr($p->getTitle(), 0, 72) .'...': $p->getTitle();?>
                                        <li>
                                            <a href="<?php echo $controller->createUrl('post/detail', array('id' => $p->getId())); ?>">
                                                <?php echo $title ?>
                                            </a>
                                            <span class="fc-g fs11"> -  <?php echo $p->getCreatedTime()->format('d/m/Y') ;?></span>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <?php $this->widget('app.widget.AjaxCalendar', array(
            'term_id' => $term->getId(),
            'fetch_child' => true,
            'route_params' => array('id' => $term->getId()),
            'day' => $post->getCreatedTime()->format('d'),
            'month' => $post->getCreatedTime()->format('m'),
            'year' => $post->getCreatedTime()->format('Y'),
        )); ?>

        <form class="search-box-common clearfix" method="get" action="<?php echo $controller->createUrl('category/default', array('id' => $term->getId())); ?>">
            <label for="keyword">
                <input id="keyword" name="keyword" value="" type="text" placeholder="<?php td('Search here...'); ?>">
            </label>
            <input type="submit" class="buttons" value="<?php td('Find') ;?>">
        </form>

        <?php $this->widget('app.widget.ArchivesWidget', array(
            'cat_id' => $term->getId(),
            'year' => $post->getCreatedTime()->format('Y')
        ))
        ?>

        <!-- Tags Cloud -->
        <div class="block tags-cloud">
        </div>
        <!--/tags cloud -->
    </div>
</div>