<?php
/** @var \Terms $term */
/** @var \Posts $post */
$page_title = $post->getTitle();
$this->document()->title .= $page_title;

$link = $controller->createUrl('post/detail', array('id' => $post->getId()));
$attachments = $post->getAttachments();
?>
<?php $this->widget('app.widget.Breadcrumbs', array(
    'links' => array(
        t('Home') => array(
            'url' => $this->document()->getBaseUrl()
        ),
        $term->getName() => array(
            'url' => $controller->createUrl('category/default', array('id' => $term->getId()))
        ),
        ($page_title)
    ),
)) ?>

<div class="row l656 fixCenter1K">
    <div class="col">
        <div class="resource-detail">
            <div class="left-info">
                <?php if ($post->getMainImg()) : ?>
                <img class="thumb-img" src="<?php echo $post->displayMainImg('175'); ?>" alt="">
                <?php endif; ?>

                <?php if ($attachments) : ?>
                <a href="#" class="btn-download">
                    Download
                    <i class="icon iArrowBlack"></i>
                </a>
                <div class="file-info">
                    <p class="rs"><span class="fw-b">File size:</span> 4MBs</p>
                    <p class="rs"><span class="fw-b">Download count:</span> 1252</p>
                </div>
                <?php endif; ?>
            </div>

            <div class="right-info">
                <h3 class="title-file"><?php echo $post->getTitle(); ?></h3>
                <div class="art-ultility clearfix">
                    <div class="date-created">
                        <?php td('Last update') ?>: <?php echo $post->getModifiedTime()->format('d F Y'); ?>
                    </div>
                    <div class="art-tool">
                        <span class="like-fb">
                            <iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $link ?>&amp;layout=button_count&amp;show_faces=false&amp;width=450&amp;action=like&amp;font&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:74px; height:20px;" allowtransparency="true"></iframe>
                        </span>
                        <span class="sep"></span>
                        <span>
                            <i class="icon iEmail"></i>
                            Email
                        </span>
                    </div>
                </div>
                <?php if ($post->getExcerpt()) : ?>
                <p class="lead-intro fw-b"><?php echo $post->getExcerpt(); ?></p>
                <?php endif; ?>
                <div class="text-content">
                    <?php echo $post->getContent(); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <form class="search-box-common clearfix" method="get" action="<?php echo $controller->createUrl('category/default', array('id' => $term->getId())); ?>">
            <label for="keyword">
                <input id="keyword" name="keyword" value="" type="text" placeholder="<?php td('Search here...'); ?>">
            </label>
            <input type="submit" class="buttons" value="<?php td('Find') ;?>">
        </form>

        <?php $controller->block('resources.col-right'); ?>
    </div>
</div>