<div id="breadcrumb" class="fixCenter1K">
        <?php foreach ($activesLink as $activeLink) : ?>
            <a href="<?php echo $activeLink['url'] ?>"><?php echo $activeLink['label'] ?></a>
            <i class="icon-angle-right"></i>
        <?php endforeach; ?>

        <?php
        if(isset($inActivesLink)) {
            foreach ($inActivesLink as $inActiveLink) : ?>
                <span class="current-page"><a><?php echo $inActiveLink ?></a></span>
            <?php endforeach; ?>
        <?php } ?>
</div>