<?php
/** @var \CalendR\Calendar $calendar */
/** @var \CalendR\Period\Year $year */
?>

<?php if ($list) :?>
    <div class="block articles-archive">
        <h3 class="title"><?php td('Archive'); ?></h3>
        <div class="block-content">
            <div class="wrap-lst clearfix">
                <?php foreach ($year as $month) :?>
                    <?php
                    $count = isset($list[$month->format('m')])? $list[$month->format('m')] : 0;
                    $link = $controller->createUrl('events/default', array(
                        'id' => $cat_id,
                        'month' => $month->format('m'),
                        'year' => $month->format('Y')
                    ));
                    ?>
                    <div class="rs item">
                        <div>
                            <a href="<?php echo $link; ?>"><span class="fw-b"><?php td($month->format('F Y')); ?></span> (<?php echo $count ?>)</a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>